// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attendance.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countAttendanceParticipants = `-- name: CountAttendanceParticipants :one
SELECT count(*)::integer AS participant_count,
       count(*) FILTER (WHERE ar.status = 'going')::integer AS going_count,
       count(*) FILTER (WHERE ar.status = 'maybe')::integer AS maybe_count,
       count(*) FILTER (WHERE ar.status = 'not_going')::integer AS not_going_count,
       count(*) FILTER (WHERE ar.status IS NULL)::integer AS unanswered_count
FROM meeting_participants mp
LEFT JOIN attendance_responses ar
  ON ar.meeting_id = mp.meeting_id AND ar.user_id = mp.user_id
WHERE mp.meeting_id = $1 AND mp.status = 'active'
`

type CountAttendanceParticipantsRow struct {
	ParticipantCount int32 `json:"participant_count"`
	GoingCount       int32 `json:"going_count"`
	MaybeCount       int32 `json:"maybe_count"`
	NotGoingCount    int32 `json:"not_going_count"`
	UnansweredCount  int32 `json:"unanswered_count"`
}

func (q *Queries) CountAttendanceParticipants(ctx context.Context, meetingID uuid.UUID) (CountAttendanceParticipantsRow, error) {
	row := q.db.QueryRow(ctx, countAttendanceParticipants, meetingID)
	var i CountAttendanceParticipantsRow
	err := row.Scan(
		&i.ParticipantCount,
		&i.GoingCount,
		&i.MaybeCount,
		&i.NotGoingCount,
		&i.UnansweredCount,
	)
	return i, err
}

const deleteAttendanceResponse = `-- name: DeleteAttendanceResponse :execrows
DELETE FROM attendance_responses
WHERE meeting_id = $1 AND user_id = $2
`

type DeleteAttendanceResponseParams struct {
	MeetingID uuid.UUID `json:"meeting_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteAttendanceResponse(ctx context.Context, arg DeleteAttendanceResponseParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAttendanceResponse, arg.MeetingID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAttendanceResponse = `-- name: GetAttendanceResponse :one
SELECT status
FROM attendance_responses
WHERE meeting_id = $1 AND user_id = $2
`

type GetAttendanceResponseParams struct {
	MeetingID uuid.UUID `json:"meeting_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) GetAttendanceResponse(ctx context.Context, arg GetAttendanceResponseParams) (string, error) {
	row := q.db.QueryRow(ctx, getAttendanceResponse, arg.MeetingID, arg.UserID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const listAttendanceParticipants = `-- name: ListAttendanceParticipants :many
SELECT mp.user_id, u.display_name, mp.role,
       COALESCE(ar.status, 'unanswered') AS status,
       ar.updated_at
FROM meeting_participants mp
JOIN users u ON u.id = mp.user_id
LEFT JOIN attendance_responses ar
  ON ar.meeting_id = mp.meeting_id AND ar.user_id = mp.user_id
WHERE mp.meeting_id = $1 AND mp.status = 'active'
ORDER BY (mp.role = 'owner') DESC, mp.joined_at, mp.user_id
LIMIT $2 OFFSET $3
`

type ListAttendanceParticipantsParams struct {
	MeetingID uuid.UUID `json:"meeting_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

type ListAttendanceParticipantsRow struct {
	UserID      uuid.UUID  `json:"user_id"`
	DisplayName string     `json:"display_name"`
	Role        string     `json:"role"`
	Status      string     `json:"status"`
	UpdatedAt   *time.Time `json:"updated_at"`
}

func (q *Queries) ListAttendanceParticipants(ctx context.Context, arg ListAttendanceParticipantsParams) ([]ListAttendanceParticipantsRow, error) {
	rows, err := q.db.Query(ctx, listAttendanceParticipants, arg.MeetingID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttendanceParticipantsRow{}
	for rows.Next() {
		var i ListAttendanceParticipantsRow
		if err := rows.Scan(
			&i.UserID,
			&i.DisplayName,
			&i.Role,
			&i.Status,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAttendanceResponse = `-- name: UpsertAttendanceResponse :exec
INSERT INTO attendance_responses (meeting_id, user_id, status)
VALUES ($1, $2, $3)
ON CONFLICT (meeting_id, user_id)
DO UPDATE SET status = EXCLUDED.status, updated_at = now()
`

type UpsertAttendanceResponseParams struct {
	MeetingID uuid.UUID `json:"meeting_id"`
	UserID    uuid.UUID `json:"user_id"`
	Status    string    `json:"status"`
}

func (q *Queries) UpsertAttendanceResponse(ctx context.Context, arg UpsertAttendanceResponseParams) error {
	_, err := q.db.Exec(ctx, upsertAttendanceResponse, arg.MeetingID, arg.UserID, arg.Status)
	return err
}
