// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: availability.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteAvailabilityVote = `-- name: DeleteAvailabilityVote :execrows
DELETE FROM availability_votes
WHERE meeting_id = $1 AND time_option_id = $2 AND user_id = $3
`

type DeleteAvailabilityVoteParams struct {
	MeetingID    uuid.UUID `json:"meeting_id"`
	TimeOptionID uuid.UUID `json:"time_option_id"`
	UserID       uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteAvailabilityVote(ctx context.Context, arg DeleteAvailabilityVoteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAvailabilityVote, arg.MeetingID, arg.TimeOptionID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTimeOptionMeetingID = `-- name: GetTimeOptionMeetingID :one
SELECT meeting_id
FROM time_options
WHERE id = $1
`

func (q *Queries) GetTimeOptionMeetingID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getTimeOptionMeetingID, id)
	var meeting_id uuid.UUID
	err := row.Scan(&meeting_id)
	return meeting_id, err
}

const listAvailabilityVotes = `-- name: ListAvailabilityVotes :many
SELECT time_option_id, user_id, status
FROM availability_votes
WHERE meeting_id = $1
ORDER BY time_option_id, user_id
`

type ListAvailabilityVotesRow struct {
	TimeOptionID uuid.UUID `json:"time_option_id"`
	UserID       uuid.UUID `json:"user_id"`
	Status       string    `json:"status"`
}

func (q *Queries) ListAvailabilityVotes(ctx context.Context, meetingID uuid.UUID) ([]ListAvailabilityVotesRow, error) {
	rows, err := q.db.Query(ctx, listAvailabilityVotes, meetingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAvailabilityVotesRow{}
	for rows.Next() {
		var i ListAvailabilityVotesRow
		if err := rows.Scan(&i.TimeOptionID, &i.UserID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAvailabilityVote = `-- name: UpsertAvailabilityVote :execrows
INSERT INTO availability_votes (
    meeting_id, time_option_id, user_id, status
) VALUES ($1, $2, $3, $4)
ON CONFLICT (time_option_id, user_id)
DO UPDATE SET status = EXCLUDED.status, updated_at = now()
WHERE availability_votes.status IS DISTINCT FROM EXCLUDED.status
`

type UpsertAvailabilityVoteParams struct {
	MeetingID    uuid.UUID `json:"meeting_id"`
	TimeOptionID uuid.UUID `json:"time_option_id"`
	UserID       uuid.UUID `json:"user_id"`
	Status       string    `json:"status"`
}

func (q *Queries) UpsertAvailabilityVote(ctx context.Context, arg UpsertAvailabilityVoteParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertAvailabilityVote,
		arg.MeetingID,
		arg.TimeOptionID,
		arg.UserID,
		arg.Status,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
