// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: decision.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveMeetingParticipants = `-- name: CountActiveMeetingParticipants :one
SELECT count(*)::integer
FROM meeting_participants
WHERE meeting_id = $1 AND status = 'active'
`

func (q *Queries) CountActiveMeetingParticipants(ctx context.Context, meetingID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countActiveMeetingParticipants, meetingID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countPlanVoteHistory = `-- name: CountPlanVoteHistory :one
SELECT count(*)::integer
FROM plan_vote_history
WHERE meeting_id = $1
`

func (q *Queries) CountPlanVoteHistory(ctx context.Context, meetingID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countPlanVoteHistory, meetingID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createPlanVoteHistory = `-- name: CreatePlanVoteHistory :exec
INSERT INTO plan_vote_history (
    id, meeting_id, user_id, action,
    previous_plan_option_id, previous_plan_title,
    new_plan_option_id, new_plan_title
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreatePlanVoteHistoryParams struct {
	ID                   uuid.UUID   `json:"id"`
	MeetingID            uuid.UUID   `json:"meeting_id"`
	UserID               uuid.UUID   `json:"user_id"`
	Action               string      `json:"action"`
	PreviousPlanOptionID *uuid.UUID  `json:"previous_plan_option_id"`
	PreviousPlanTitle    pgtype.Text `json:"previous_plan_title"`
	NewPlanOptionID      *uuid.UUID  `json:"new_plan_option_id"`
	NewPlanTitle         pgtype.Text `json:"new_plan_title"`
}

func (q *Queries) CreatePlanVoteHistory(ctx context.Context, arg CreatePlanVoteHistoryParams) error {
	_, err := q.db.Exec(ctx, createPlanVoteHistory,
		arg.ID,
		arg.MeetingID,
		arg.UserID,
		arg.Action,
		arg.PreviousPlanOptionID,
		arg.PreviousPlanTitle,
		arg.NewPlanOptionID,
		arg.NewPlanTitle,
	)
	return err
}

const deletePlanVote = `-- name: DeletePlanVote :execrows
DELETE FROM plan_votes
WHERE meeting_id = $1 AND user_id = $2
`

type DeletePlanVoteParams struct {
	MeetingID uuid.UUID `json:"meeting_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) DeletePlanVote(ctx context.Context, arg DeletePlanVoteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePlanVote, arg.MeetingID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCurrentPlanVote = `-- name: GetCurrentPlanVote :one
SELECT pv.plan_option_id, po.title
FROM plan_votes pv
JOIN plan_options po
  ON po.meeting_id = pv.meeting_id AND po.id = pv.plan_option_id
WHERE pv.meeting_id = $1 AND pv.user_id = $2
`

type GetCurrentPlanVoteParams struct {
	MeetingID uuid.UUID `json:"meeting_id"`
	UserID    uuid.UUID `json:"user_id"`
}

type GetCurrentPlanVoteRow struct {
	PlanOptionID uuid.UUID `json:"plan_option_id"`
	Title        string    `json:"title"`
}

func (q *Queries) GetCurrentPlanVote(ctx context.Context, arg GetCurrentPlanVoteParams) (GetCurrentPlanVoteRow, error) {
	row := q.db.QueryRow(ctx, getCurrentPlanVote, arg.MeetingID, arg.UserID)
	var i GetCurrentPlanVoteRow
	err := row.Scan(&i.PlanOptionID, &i.Title)
	return i, err
}

const getMeetingDecisionForOwnerForUpdate = `-- name: GetMeetingDecisionForOwnerForUpdate :one
SELECT state, selected_plan_option_id, selected_time_option_id
FROM meetings
WHERE id = $1 AND owner_id = $2
FOR UPDATE
`

type GetMeetingDecisionForOwnerForUpdateParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"owner_id"`
}

type GetMeetingDecisionForOwnerForUpdateRow struct {
	State                string     `json:"state"`
	SelectedPlanOptionID *uuid.UUID `json:"selected_plan_option_id"`
	SelectedTimeOptionID *uuid.UUID `json:"selected_time_option_id"`
}

func (q *Queries) GetMeetingDecisionForOwnerForUpdate(ctx context.Context, arg GetMeetingDecisionForOwnerForUpdateParams) (GetMeetingDecisionForOwnerForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getMeetingDecisionForOwnerForUpdate, arg.ID, arg.OwnerID)
	var i GetMeetingDecisionForOwnerForUpdateRow
	err := row.Scan(&i.State, &i.SelectedPlanOptionID, &i.SelectedTimeOptionID)
	return i, err
}

const getPlanOptionForVote = `-- name: GetPlanOptionForVote :one
SELECT id, title
FROM plan_options
WHERE meeting_id = $1 AND id = $2
`

type GetPlanOptionForVoteParams struct {
	MeetingID uuid.UUID `json:"meeting_id"`
	ID        uuid.UUID `json:"id"`
}

type GetPlanOptionForVoteRow struct {
	ID    uuid.UUID `json:"id"`
	Title string    `json:"title"`
}

func (q *Queries) GetPlanOptionForVote(ctx context.Context, arg GetPlanOptionForVoteParams) (GetPlanOptionForVoteRow, error) {
	row := q.db.QueryRow(ctx, getPlanOptionForVote, arg.MeetingID, arg.ID)
	var i GetPlanOptionForVoteRow
	err := row.Scan(&i.ID, &i.Title)
	return i, err
}

const getTimeOptionForDecision = `-- name: GetTimeOptionForDecision :one
SELECT id, plan_option_id
FROM time_options
WHERE meeting_id = $1 AND id = $2
`

type GetTimeOptionForDecisionParams struct {
	MeetingID uuid.UUID `json:"meeting_id"`
	ID        uuid.UUID `json:"id"`
}

type GetTimeOptionForDecisionRow struct {
	ID           uuid.UUID  `json:"id"`
	PlanOptionID *uuid.UUID `json:"plan_option_id"`
}

func (q *Queries) GetTimeOptionForDecision(ctx context.Context, arg GetTimeOptionForDecisionParams) (GetTimeOptionForDecisionRow, error) {
	row := q.db.QueryRow(ctx, getTimeOptionForDecision, arg.MeetingID, arg.ID)
	var i GetTimeOptionForDecisionRow
	err := row.Scan(&i.ID, &i.PlanOptionID)
	return i, err
}

const listPlanVoteHistory = `-- name: ListPlanVoteHistory :many
SELECT h.id, h.user_id, u.display_name, h.action,
       h.previous_plan_option_id, h.previous_plan_title,
       h.new_plan_option_id, h.new_plan_title, h.created_at
FROM plan_vote_history h
JOIN users u ON u.id = h.user_id
WHERE h.meeting_id = $1
ORDER BY h.created_at DESC, h.id DESC
LIMIT $2 OFFSET $3
`

type ListPlanVoteHistoryParams struct {
	MeetingID uuid.UUID `json:"meeting_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

type ListPlanVoteHistoryRow struct {
	ID                   uuid.UUID   `json:"id"`
	UserID               uuid.UUID   `json:"user_id"`
	DisplayName          string      `json:"display_name"`
	Action               string      `json:"action"`
	PreviousPlanOptionID *uuid.UUID  `json:"previous_plan_option_id"`
	PreviousPlanTitle    pgtype.Text `json:"previous_plan_title"`
	NewPlanOptionID      *uuid.UUID  `json:"new_plan_option_id"`
	NewPlanTitle         pgtype.Text `json:"new_plan_title"`
	CreatedAt            time.Time   `json:"created_at"`
}

func (q *Queries) ListPlanVoteHistory(ctx context.Context, arg ListPlanVoteHistoryParams) ([]ListPlanVoteHistoryRow, error) {
	rows, err := q.db.Query(ctx, listPlanVoteHistory, arg.MeetingID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlanVoteHistoryRow{}
	for rows.Next() {
		var i ListPlanVoteHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DisplayName,
			&i.Action,
			&i.PreviousPlanOptionID,
			&i.PreviousPlanTitle,
			&i.NewPlanOptionID,
			&i.NewPlanTitle,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlanVoteOptions = `-- name: ListPlanVoteOptions :many
SELECT po.id, po.title, po.description, po.position,
       count(pv.user_id)::integer AS vote_count,
       EXISTS (
           SELECT 1
           FROM plan_votes mine
           WHERE mine.meeting_id = po.meeting_id
             AND mine.user_id = $2
             AND mine.plan_option_id = po.id
       ) AS selected_by_user
FROM plan_options po
LEFT JOIN plan_votes pv
  ON pv.meeting_id = po.meeting_id AND pv.plan_option_id = po.id
WHERE po.meeting_id = $1
GROUP BY po.id, po.title, po.description, po.position, po.meeting_id
ORDER BY po.position, po.id
`

type ListPlanVoteOptionsParams struct {
	MeetingID uuid.UUID `json:"meeting_id"`
	UserID    uuid.UUID `json:"user_id"`
}

type ListPlanVoteOptionsRow struct {
	ID             uuid.UUID `json:"id"`
	Title          string    `json:"title"`
	Description    string    `json:"description"`
	Position       int16     `json:"position"`
	VoteCount      int32     `json:"vote_count"`
	SelectedByUser bool      `json:"selected_by_user"`
}

func (q *Queries) ListPlanVoteOptions(ctx context.Context, arg ListPlanVoteOptionsParams) ([]ListPlanVoteOptionsRow, error) {
	rows, err := q.db.Query(ctx, listPlanVoteOptions, arg.MeetingID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlanVoteOptionsRow{}
	for rows.Next() {
		var i ListPlanVoteOptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Position,
			&i.VoteCount,
			&i.SelectedByUser,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlanVoteResponses = `-- name: ListPlanVoteResponses :many
SELECT pv.user_id, u.display_name, pv.plan_option_id, pv.updated_at
FROM plan_votes pv
JOIN users u ON u.id = pv.user_id
WHERE pv.meeting_id = $1
ORDER BY pv.updated_at, pv.user_id
`

type ListPlanVoteResponsesRow struct {
	UserID       uuid.UUID `json:"user_id"`
	DisplayName  string    `json:"display_name"`
	PlanOptionID uuid.UUID `json:"plan_option_id"`
	UpdatedAt    time.Time `json:"updated_at"`
}

func (q *Queries) ListPlanVoteResponses(ctx context.Context, meetingID uuid.UUID) ([]ListPlanVoteResponsesRow, error) {
	rows, err := q.db.Query(ctx, listPlanVoteResponses, meetingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlanVoteResponsesRow{}
	for rows.Next() {
		var i ListPlanVoteResponsesRow
		if err := rows.Scan(
			&i.UserID,
			&i.DisplayName,
			&i.PlanOptionID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scheduleMeeting = `-- name: ScheduleMeeting :exec
UPDATE meetings
SET state = 'scheduled',
    selected_plan_option_id = $2,
    selected_time_option_id = $3,
    version = version + 1,
    updated_at = now()
WHERE id = $1
`

type ScheduleMeetingParams struct {
	ID                   uuid.UUID  `json:"id"`
	SelectedPlanOptionID *uuid.UUID `json:"selected_plan_option_id"`
	SelectedTimeOptionID *uuid.UUID `json:"selected_time_option_id"`
}

func (q *Queries) ScheduleMeeting(ctx context.Context, arg ScheduleMeetingParams) error {
	_, err := q.db.Exec(ctx, scheduleMeeting, arg.ID, arg.SelectedPlanOptionID, arg.SelectedTimeOptionID)
	return err
}

const upsertPlanVote = `-- name: UpsertPlanVote :exec
INSERT INTO plan_votes (meeting_id, user_id, plan_option_id)
VALUES ($1, $2, $3)
ON CONFLICT (meeting_id, user_id)
DO UPDATE SET plan_option_id = EXCLUDED.plan_option_id, updated_at = now()
`

type UpsertPlanVoteParams struct {
	MeetingID    uuid.UUID `json:"meeting_id"`
	UserID       uuid.UUID `json:"user_id"`
	PlanOptionID uuid.UUID `json:"plan_option_id"`
}

func (q *Queries) UpsertPlanVote(ctx context.Context, arg UpsertPlanVoteParams) error {
	_, err := q.db.Exec(ctx, upsertPlanVote, arg.MeetingID, arg.UserID, arg.PlanOptionID)
	return err
}
