// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: friendships.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acceptFriendRequest = `-- name: AcceptFriendRequest :one
UPDATE friendships
SET status = 'accepted', responded_at = now(), updated_at = now()
WHERE id = $1 AND addressee_id = $2 AND status = 'pending'
RETURNING id, requester_id, addressee_id, status, responded_at, created_at, updated_at
`

type AcceptFriendRequestParams struct {
	ID          uuid.UUID `json:"id"`
	AddresseeID uuid.UUID `json:"addressee_id"`
}

func (q *Queries) AcceptFriendRequest(ctx context.Context, arg AcceptFriendRequestParams) (Friendship, error) {
	row := q.db.QueryRow(ctx, acceptFriendRequest, arg.ID, arg.AddresseeID)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.AddresseeID,
		&i.Status,
		&i.RespondedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countFriends = `-- name: CountFriends :one
SELECT count(*)
FROM friendships
WHERE status = 'accepted'
  AND (requester_id = $1 OR addressee_id = $1)
`

func (q *Queries) CountFriends(ctx context.Context, requesterID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFriends, requesterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countIncomingFriendRequests = `-- name: CountIncomingFriendRequests :one
SELECT count(*)
FROM friendships
WHERE addressee_id = $1 AND status = 'pending'
`

func (q *Queries) CountIncomingFriendRequests(ctx context.Context, addresseeID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countIncomingFriendRequests, addresseeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOutgoingFriendRequests = `-- name: CountOutgoingFriendRequests :one
SELECT count(*)
FROM friendships
WHERE requester_id = $1 AND status = 'pending'
`

func (q *Queries) CountOutgoingFriendRequests(ctx context.Context, requesterID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOutgoingFriendRequests, requesterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAcceptedFriendship = `-- name: DeleteAcceptedFriendship :execrows
DELETE FROM friendships
WHERE status = 'accepted'
  AND ((requester_id = $1 AND addressee_id = $2)
    OR (requester_id = $2 AND addressee_id = $1))
`

type DeleteAcceptedFriendshipParams struct {
	RequesterID uuid.UUID `json:"requester_id"`
	AddresseeID uuid.UUID `json:"addressee_id"`
}

func (q *Queries) DeleteAcceptedFriendship(ctx context.Context, arg DeleteAcceptedFriendshipParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAcceptedFriendship, arg.RequesterID, arg.AddresseeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePendingFriendRequest = `-- name: DeletePendingFriendRequest :execrows
DELETE FROM friendships
WHERE id = $1
  AND status = 'pending'
  AND (requester_id = $2 OR addressee_id = $2)
`

type DeletePendingFriendRequestParams struct {
	ID          uuid.UUID `json:"id"`
	RequesterID uuid.UUID `json:"requester_id"`
}

func (q *Queries) DeletePendingFriendRequest(ctx context.Context, arg DeletePendingFriendRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePendingFriendRequest, arg.ID, arg.RequesterID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getFriendshipByIDForUpdate = `-- name: GetFriendshipByIDForUpdate :one
SELECT id, requester_id, addressee_id, status, responded_at, created_at, updated_at
FROM friendships
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetFriendshipByIDForUpdate(ctx context.Context, id uuid.UUID) (Friendship, error) {
	row := q.db.QueryRow(ctx, getFriendshipByIDForUpdate, id)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.AddresseeID,
		&i.Status,
		&i.RespondedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFriendshipByPair = `-- name: GetFriendshipByPair :one
SELECT id, requester_id, addressee_id, status, responded_at, created_at, updated_at
FROM friendships
WHERE (requester_id = $1 AND addressee_id = $2)
   OR (requester_id = $2 AND addressee_id = $1)
`

type GetFriendshipByPairParams struct {
	RequesterID uuid.UUID `json:"requester_id"`
	AddresseeID uuid.UUID `json:"addressee_id"`
}

func (q *Queries) GetFriendshipByPair(ctx context.Context, arg GetFriendshipByPairParams) (Friendship, error) {
	row := q.db.QueryRow(ctx, getFriendshipByPair, arg.RequesterID, arg.AddresseeID)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.AddresseeID,
		&i.Status,
		&i.RespondedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertFriendRequest = `-- name: InsertFriendRequest :one
INSERT INTO friendships (id, requester_id, addressee_id)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
RETURNING id, requester_id, addressee_id, status, responded_at, created_at, updated_at
`

type InsertFriendRequestParams struct {
	ID          uuid.UUID `json:"id"`
	RequesterID uuid.UUID `json:"requester_id"`
	AddresseeID uuid.UUID `json:"addressee_id"`
}

func (q *Queries) InsertFriendRequest(ctx context.Context, arg InsertFriendRequestParams) (Friendship, error) {
	row := q.db.QueryRow(ctx, insertFriendRequest, arg.ID, arg.RequesterID, arg.AddresseeID)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.AddresseeID,
		&i.Status,
		&i.RespondedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFriends = `-- name: ListFriends :many
SELECT f.id,
       u.id AS user_id, u.nickname, u.display_name, u.avatar_url, u.avatar_revision,
       f.updated_at
FROM friendships f
JOIN users u ON u.id = CASE
    WHEN f.requester_id = $1 THEN f.addressee_id
    ELSE f.requester_id
END
WHERE f.status = 'accepted'
  AND (f.requester_id = $1 OR f.addressee_id = $1)
ORDER BY lower(u.display_name), u.nickname, u.id
LIMIT $3 OFFSET $2
`

type ListFriendsParams struct {
	UserID       uuid.UUID `json:"user_id"`
	ResultOffset int32     `json:"result_offset"`
	ResultLimit  int32     `json:"result_limit"`
}

type ListFriendsRow struct {
	ID             uuid.UUID   `json:"id"`
	UserID         uuid.UUID   `json:"user_id"`
	Nickname       string      `json:"nickname"`
	DisplayName    string      `json:"display_name"`
	AvatarUrl      pgtype.Text `json:"avatar_url"`
	AvatarRevision pgtype.Int8 `json:"avatar_revision"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

func (q *Queries) ListFriends(ctx context.Context, arg ListFriendsParams) ([]ListFriendsRow, error) {
	rows, err := q.db.Query(ctx, listFriends, arg.UserID, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFriendsRow{}
	for rows.Next() {
		var i ListFriendsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Nickname,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.AvatarRevision,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomingFriendRequests = `-- name: ListIncomingFriendRequests :many
SELECT f.id,
       u.id AS user_id, u.nickname, u.display_name, u.avatar_url, u.avatar_revision,
       f.created_at
FROM friendships f
JOIN users u ON u.id = f.requester_id
WHERE f.addressee_id = $1 AND f.status = 'pending'
ORDER BY f.created_at DESC, f.id
LIMIT $3 OFFSET $2
`

type ListIncomingFriendRequestsParams struct {
	UserID       uuid.UUID `json:"user_id"`
	ResultOffset int32     `json:"result_offset"`
	ResultLimit  int32     `json:"result_limit"`
}

type ListIncomingFriendRequestsRow struct {
	ID             uuid.UUID   `json:"id"`
	UserID         uuid.UUID   `json:"user_id"`
	Nickname       string      `json:"nickname"`
	DisplayName    string      `json:"display_name"`
	AvatarUrl      pgtype.Text `json:"avatar_url"`
	AvatarRevision pgtype.Int8 `json:"avatar_revision"`
	CreatedAt      time.Time   `json:"created_at"`
}

func (q *Queries) ListIncomingFriendRequests(ctx context.Context, arg ListIncomingFriendRequestsParams) ([]ListIncomingFriendRequestsRow, error) {
	rows, err := q.db.Query(ctx, listIncomingFriendRequests, arg.UserID, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIncomingFriendRequestsRow{}
	for rows.Next() {
		var i ListIncomingFriendRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Nickname,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.AvatarRevision,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutgoingFriendRequests = `-- name: ListOutgoingFriendRequests :many
SELECT f.id,
       u.id AS user_id, u.nickname, u.display_name, u.avatar_url, u.avatar_revision,
       f.created_at
FROM friendships f
JOIN users u ON u.id = f.addressee_id
WHERE f.requester_id = $1 AND f.status = 'pending'
ORDER BY f.created_at DESC, f.id
LIMIT $3 OFFSET $2
`

type ListOutgoingFriendRequestsParams struct {
	UserID       uuid.UUID `json:"user_id"`
	ResultOffset int32     `json:"result_offset"`
	ResultLimit  int32     `json:"result_limit"`
}

type ListOutgoingFriendRequestsRow struct {
	ID             uuid.UUID   `json:"id"`
	UserID         uuid.UUID   `json:"user_id"`
	Nickname       string      `json:"nickname"`
	DisplayName    string      `json:"display_name"`
	AvatarUrl      pgtype.Text `json:"avatar_url"`
	AvatarRevision pgtype.Int8 `json:"avatar_revision"`
	CreatedAt      time.Time   `json:"created_at"`
}

func (q *Queries) ListOutgoingFriendRequests(ctx context.Context, arg ListOutgoingFriendRequestsParams) ([]ListOutgoingFriendRequestsRow, error) {
	rows, err := q.db.Query(ctx, listOutgoingFriendRequests, arg.UserID, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOutgoingFriendRequestsRow{}
	for rows.Next() {
		var i ListOutgoingFriendRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Nickname,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.AvatarRevision,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsersByNickname = `-- name: SearchUsersByNickname :many
SELECT u.id, u.nickname, u.display_name, u.avatar_url, u.avatar_revision,
       f.id AS friendship_id,
       CASE
           WHEN f.status = 'accepted' THEN 'friend'
           WHEN f.status = 'pending' AND f.requester_id = $1 THEN 'outgoing'
           WHEN f.status = 'pending' THEN 'incoming'
           ELSE 'none'
       END AS relationship
FROM users u
LEFT JOIN friendships f
  ON (f.requester_id = $1 AND f.addressee_id = u.id)
  OR (f.addressee_id = $1 AND f.requester_id = u.id)
WHERE u.id <> $1
  AND u.nickname LIKE replace($2::text, '_', '\_') || '%' ESCAPE '\'
ORDER BY (u.nickname = $2::text) DESC, u.nickname
LIMIT $3
`

type SearchUsersByNicknameParams struct {
	UserID         uuid.UUID `json:"user_id"`
	NicknamePrefix string    `json:"nickname_prefix"`
	ResultLimit    int32     `json:"result_limit"`
}

type SearchUsersByNicknameRow struct {
	ID             uuid.UUID   `json:"id"`
	Nickname       string      `json:"nickname"`
	DisplayName    string      `json:"display_name"`
	AvatarUrl      pgtype.Text `json:"avatar_url"`
	AvatarRevision pgtype.Int8 `json:"avatar_revision"`
	FriendshipID   *uuid.UUID  `json:"friendship_id"`
	Relationship   string      `json:"relationship"`
}

func (q *Queries) SearchUsersByNickname(ctx context.Context, arg SearchUsersByNicknameParams) ([]SearchUsersByNicknameRow, error) {
	rows, err := q.db.Query(ctx, searchUsersByNickname, arg.UserID, arg.NicknamePrefix, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUsersByNicknameRow{}
	for rows.Next() {
		var i SearchUsersByNicknameRow
		if err := rows.Scan(
			&i.ID,
			&i.Nickname,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.AvatarRevision,
			&i.FriendshipID,
			&i.Relationship,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
