// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: meetings.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addMeetingParticipant = `-- name: AddMeetingParticipant :exec
INSERT INTO meeting_participants (meeting_id, user_id, role, status)
VALUES ($1, $2, $3, 'active')
`

type AddMeetingParticipantParams struct {
	MeetingID uuid.UUID `json:"meeting_id"`
	UserID    uuid.UUID `json:"user_id"`
	Role      string    `json:"role"`
}

func (q *Queries) AddMeetingParticipant(ctx context.Context, arg AddMeetingParticipantParams) error {
	_, err := q.db.Exec(ctx, addMeetingParticipant, arg.MeetingID, arg.UserID, arg.Role)
	return err
}

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :exec
UPDATE idempotency_keys
SET status_code = $4, response_body = $5
WHERE user_id = $1 AND operation = $2 AND key = $3
`

type CompleteIdempotencyKeyParams struct {
	UserID       uuid.UUID   `json:"user_id"`
	Operation    string      `json:"operation"`
	Key          string      `json:"key"`
	StatusCode   pgtype.Int4 `json:"status_code"`
	ResponseBody []byte      `json:"response_body"`
}

func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, completeIdempotencyKey,
		arg.UserID,
		arg.Operation,
		arg.Key,
		arg.StatusCode,
		arg.ResponseBody,
	)
	return err
}

const createMeeting = `-- name: CreateMeeting :one
INSERT INTO meetings (
    id, owner_id, title, description, event_type, coordination_mode,
    cover_url, location_name, location_url, timezone
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, owner_id, title, description, cover_url, location_name, location_url,
          event_type, coordination_mode, timezone, state,
          selected_plan_option_id, selected_time_option_id,
          version, created_at, updated_at
`

type CreateMeetingParams struct {
	ID               uuid.UUID   `json:"id"`
	OwnerID          uuid.UUID   `json:"owner_id"`
	Title            string      `json:"title"`
	Description      string      `json:"description"`
	EventType        string      `json:"event_type"`
	CoordinationMode string      `json:"coordination_mode"`
	CoverUrl         pgtype.Text `json:"cover_url"`
	LocationName     pgtype.Text `json:"location_name"`
	LocationUrl      pgtype.Text `json:"location_url"`
	Timezone         string      `json:"timezone"`
}

type CreateMeetingRow struct {
	ID                   uuid.UUID   `json:"id"`
	OwnerID              uuid.UUID   `json:"owner_id"`
	Title                string      `json:"title"`
	Description          string      `json:"description"`
	CoverUrl             pgtype.Text `json:"cover_url"`
	LocationName         pgtype.Text `json:"location_name"`
	LocationUrl          pgtype.Text `json:"location_url"`
	EventType            string      `json:"event_type"`
	CoordinationMode     string      `json:"coordination_mode"`
	Timezone             string      `json:"timezone"`
	State                string      `json:"state"`
	SelectedPlanOptionID *uuid.UUID  `json:"selected_plan_option_id"`
	SelectedTimeOptionID *uuid.UUID  `json:"selected_time_option_id"`
	Version              int64       `json:"version"`
	CreatedAt            time.Time   `json:"created_at"`
	UpdatedAt            time.Time   `json:"updated_at"`
}

func (q *Queries) CreateMeeting(ctx context.Context, arg CreateMeetingParams) (CreateMeetingRow, error) {
	row := q.db.QueryRow(ctx, createMeeting,
		arg.ID,
		arg.OwnerID,
		arg.Title,
		arg.Description,
		arg.EventType,
		arg.CoordinationMode,
		arg.CoverUrl,
		arg.LocationName,
		arg.LocationUrl,
		arg.Timezone,
	)
	var i CreateMeetingRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.CoverUrl,
		&i.LocationName,
		&i.LocationUrl,
		&i.EventType,
		&i.CoordinationMode,
		&i.Timezone,
		&i.State,
		&i.SelectedPlanOptionID,
		&i.SelectedTimeOptionID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT user_id, operation, key, request_hash, status_code, response_body, created_at, expires_at
FROM idempotency_keys
WHERE user_id = $1 AND operation = $2 AND key = $3
`

type GetIdempotencyKeyParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Operation string    `json:"operation"`
	Key       string    `json:"key"`
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.UserID, arg.Operation, arg.Key)
	var i IdempotencyKey
	err := row.Scan(
		&i.UserID,
		&i.Operation,
		&i.Key,
		&i.RequestHash,
		&i.StatusCode,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getMeetingForUser = `-- name: GetMeetingForUser :one
SELECT m.id, m.owner_id, m.title, m.description, m.cover_url, m.location_name,
       m.location_url, m.event_type, m.coordination_mode, m.timezone, m.state, m.selected_plan_option_id,
       m.selected_time_option_id, m.version, m.created_at, m.updated_at,
       mp.role AS participant_role
FROM meetings m
JOIN meeting_participants mp ON mp.meeting_id = m.id
WHERE m.id = $1 AND mp.user_id = $2 AND mp.status = 'active'
`

type GetMeetingForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetMeetingForUserRow struct {
	ID                   uuid.UUID   `json:"id"`
	OwnerID              uuid.UUID   `json:"owner_id"`
	Title                string      `json:"title"`
	Description          string      `json:"description"`
	CoverUrl             pgtype.Text `json:"cover_url"`
	LocationName         pgtype.Text `json:"location_name"`
	LocationUrl          pgtype.Text `json:"location_url"`
	EventType            string      `json:"event_type"`
	CoordinationMode     string      `json:"coordination_mode"`
	Timezone             string      `json:"timezone"`
	State                string      `json:"state"`
	SelectedPlanOptionID *uuid.UUID  `json:"selected_plan_option_id"`
	SelectedTimeOptionID *uuid.UUID  `json:"selected_time_option_id"`
	Version              int64       `json:"version"`
	CreatedAt            time.Time   `json:"created_at"`
	UpdatedAt            time.Time   `json:"updated_at"`
	ParticipantRole      string      `json:"participant_role"`
}

func (q *Queries) GetMeetingForUser(ctx context.Context, arg GetMeetingForUserParams) (GetMeetingForUserRow, error) {
	row := q.db.QueryRow(ctx, getMeetingForUser, arg.ID, arg.UserID)
	var i GetMeetingForUserRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.CoverUrl,
		&i.LocationName,
		&i.LocationUrl,
		&i.EventType,
		&i.CoordinationMode,
		&i.Timezone,
		&i.State,
		&i.SelectedPlanOptionID,
		&i.SelectedTimeOptionID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParticipantRole,
	)
	return i, err
}

const listMeetingsForUser = `-- name: ListMeetingsForUser :many
SELECT m.id, m.owner_id, m.title, m.description, m.cover_url, m.location_name,
       m.location_url, m.event_type, m.coordination_mode, m.timezone, m.state, m.selected_plan_option_id,
       m.selected_time_option_id, m.version, m.created_at, m.updated_at,
       mp.joined_at AS participant_joined_at,
       selected_time.starts_at AS selected_starts_at,
       selected_time.ends_at AS selected_ends_at,
       CASE
           WHEN m.coordination_mode = 'fixed' THEN COALESCE(ar.status, 'unanswered')
           ELSE ''
       END AS my_attendance_status
FROM meetings m
JOIN meeting_participants mp ON mp.meeting_id = m.id
LEFT JOIN time_options selected_time ON selected_time.id = m.selected_time_option_id
LEFT JOIN attendance_responses ar ON ar.meeting_id = m.id AND ar.user_id = mp.user_id
WHERE mp.user_id = $1 AND mp.status = 'active'
ORDER BY m.created_at DESC, m.id DESC
LIMIT $2 OFFSET $3
`

type ListMeetingsForUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListMeetingsForUserRow struct {
	ID                   uuid.UUID   `json:"id"`
	OwnerID              uuid.UUID   `json:"owner_id"`
	Title                string      `json:"title"`
	Description          string      `json:"description"`
	CoverUrl             pgtype.Text `json:"cover_url"`
	LocationName         pgtype.Text `json:"location_name"`
	LocationUrl          pgtype.Text `json:"location_url"`
	EventType            string      `json:"event_type"`
	CoordinationMode     string      `json:"coordination_mode"`
	Timezone             string      `json:"timezone"`
	State                string      `json:"state"`
	SelectedPlanOptionID *uuid.UUID  `json:"selected_plan_option_id"`
	SelectedTimeOptionID *uuid.UUID  `json:"selected_time_option_id"`
	Version              int64       `json:"version"`
	CreatedAt            time.Time   `json:"created_at"`
	UpdatedAt            time.Time   `json:"updated_at"`
	ParticipantJoinedAt  time.Time   `json:"participant_joined_at"`
	SelectedStartsAt     *time.Time  `json:"selected_starts_at"`
	SelectedEndsAt       *time.Time  `json:"selected_ends_at"`
	MyAttendanceStatus   string      `json:"my_attendance_status"`
}

func (q *Queries) ListMeetingsForUser(ctx context.Context, arg ListMeetingsForUserParams) ([]ListMeetingsForUserRow, error) {
	rows, err := q.db.Query(ctx, listMeetingsForUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMeetingsForUserRow{}
	for rows.Next() {
		var i ListMeetingsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Description,
			&i.CoverUrl,
			&i.LocationName,
			&i.LocationUrl,
			&i.EventType,
			&i.CoordinationMode,
			&i.Timezone,
			&i.State,
			&i.SelectedPlanOptionID,
			&i.SelectedTimeOptionID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParticipantJoinedAt,
			&i.SelectedStartsAt,
			&i.SelectedEndsAt,
			&i.MyAttendanceStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reserveIdempotencyKey = `-- name: ReserveIdempotencyKey :execrows
INSERT INTO idempotency_keys (
    user_id, operation, key, request_hash, expires_at
) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, operation, key) DO NOTHING
`

type ReserveIdempotencyKeyParams struct {
	UserID      uuid.UUID `json:"user_id"`
	Operation   string    `json:"operation"`
	Key         string    `json:"key"`
	RequestHash []byte    `json:"request_hash"`
	ExpiresAt   time.Time `json:"expires_at"`
}

func (q *Queries) ReserveIdempotencyKey(ctx context.Context, arg ReserveIdempotencyKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, reserveIdempotencyKey,
		arg.UserID,
		arg.Operation,
		arg.Key,
		arg.RequestHash,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateDraftMeeting = `-- name: UpdateDraftMeeting :one
UPDATE meetings
SET title = $2,
    description = $3,
    event_type = $4,
    cover_url = $5,
    location_name = $6,
    location_url = $7,
    version = version + 1,
    updated_at = now()
WHERE id = $1
RETURNING id, owner_id, title, description, cover_url, location_name, location_url,
          event_type, coordination_mode, timezone, state,
          selected_plan_option_id, selected_time_option_id,
          version, created_at, updated_at
`

type UpdateDraftMeetingParams struct {
	ID           uuid.UUID   `json:"id"`
	Title        string      `json:"title"`
	Description  string      `json:"description"`
	EventType    string      `json:"event_type"`
	CoverUrl     pgtype.Text `json:"cover_url"`
	LocationName pgtype.Text `json:"location_name"`
	LocationUrl  pgtype.Text `json:"location_url"`
}

type UpdateDraftMeetingRow struct {
	ID                   uuid.UUID   `json:"id"`
	OwnerID              uuid.UUID   `json:"owner_id"`
	Title                string      `json:"title"`
	Description          string      `json:"description"`
	CoverUrl             pgtype.Text `json:"cover_url"`
	LocationName         pgtype.Text `json:"location_name"`
	LocationUrl          pgtype.Text `json:"location_url"`
	EventType            string      `json:"event_type"`
	CoordinationMode     string      `json:"coordination_mode"`
	Timezone             string      `json:"timezone"`
	State                string      `json:"state"`
	SelectedPlanOptionID *uuid.UUID  `json:"selected_plan_option_id"`
	SelectedTimeOptionID *uuid.UUID  `json:"selected_time_option_id"`
	Version              int64       `json:"version"`
	CreatedAt            time.Time   `json:"created_at"`
	UpdatedAt            time.Time   `json:"updated_at"`
}

func (q *Queries) UpdateDraftMeeting(ctx context.Context, arg UpdateDraftMeetingParams) (UpdateDraftMeetingRow, error) {
	row := q.db.QueryRow(ctx, updateDraftMeeting,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.EventType,
		arg.CoverUrl,
		arg.LocationName,
		arg.LocationUrl,
	)
	var i UpdateDraftMeetingRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.CoverUrl,
		&i.LocationName,
		&i.LocationUrl,
		&i.EventType,
		&i.CoordinationMode,
		&i.Timezone,
		&i.State,
		&i.SelectedPlanOptionID,
		&i.SelectedTimeOptionID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
