// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AttendanceResponse struct {
	MeetingID uuid.UUID `json:"meeting_id"`
	UserID    uuid.UUID `json:"user_id"`
	Status    string    `json:"status"`
	UpdatedAt time.Time `json:"updated_at"`
}

type AvailabilityVote struct {
	MeetingID    uuid.UUID `json:"meeting_id"`
	TimeOptionID uuid.UUID `json:"time_option_id"`
	UserID       uuid.UUID `json:"user_id"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type Friendship struct {
	ID          uuid.UUID  `json:"id"`
	RequesterID uuid.UUID  `json:"requester_id"`
	AddresseeID uuid.UUID  `json:"addressee_id"`
	Status      string     `json:"status"`
	RespondedAt *time.Time `json:"responded_at"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
}

type IdempotencyKey struct {
	UserID       uuid.UUID   `json:"user_id"`
	Operation    string      `json:"operation"`
	Key          string      `json:"key"`
	RequestHash  []byte      `json:"request_hash"`
	StatusCode   pgtype.Int4 `json:"status_code"`
	ResponseBody []byte      `json:"response_body"`
	CreatedAt    time.Time   `json:"created_at"`
	ExpiresAt    time.Time   `json:"expires_at"`
}

type Invitation struct {
	ID             uuid.UUID  `json:"id"`
	MeetingID      uuid.UUID  `json:"meeting_id"`
	CreatedBy      uuid.UUID  `json:"created_by"`
	SecretHash     []byte     `json:"secret_hash"`
	IdempotencyKey string     `json:"idempotency_key"`
	DefaultRole    string     `json:"default_role"`
	ExpiresAt      time.Time  `json:"expires_at"`
	RevokedAt      *time.Time `json:"revoked_at"`
	CreatedAt      time.Time  `json:"created_at"`
}

type Meeting struct {
	ID                   uuid.UUID   `json:"id"`
	OwnerID              uuid.UUID   `json:"owner_id"`
	Title                string      `json:"title"`
	Description          string      `json:"description"`
	CoverUrl             pgtype.Text `json:"cover_url"`
	LocationName         pgtype.Text `json:"location_name"`
	LocationUrl          pgtype.Text `json:"location_url"`
	EventType            string      `json:"event_type"`
	Timezone             string      `json:"timezone"`
	State                string      `json:"state"`
	SelectedPlanOptionID *uuid.UUID  `json:"selected_plan_option_id"`
	SelectedTimeOptionID *uuid.UUID  `json:"selected_time_option_id"`
	Version              int64       `json:"version"`
	CreatedAt            time.Time   `json:"created_at"`
	UpdatedAt            time.Time   `json:"updated_at"`
	CoordinationMode     string      `json:"coordination_mode"`
}

type MeetingNote struct {
	MeetingID uuid.UUID `json:"meeting_id"`
	UserID    uuid.UUID `json:"user_id"`
	Text      string    `json:"text"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type MeetingParticipant struct {
	MeetingID uuid.UUID `json:"meeting_id"`
	UserID    uuid.UUID `json:"user_id"`
	Role      string    `json:"role"`
	Status    string    `json:"status"`
	JoinedAt  time.Time `json:"joined_at"`
}

type MeetingPhoto struct {
	MeetingID   uuid.UUID `json:"meeting_id"`
	ContentType string    `json:"content_type"`
	Content     []byte    `json:"content"`
	ContentHash []byte    `json:"content_hash"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type PlanOption struct {
	ID             uuid.UUID `json:"id"`
	MeetingID      uuid.UUID `json:"meeting_id"`
	Title          string    `json:"title"`
	Description    string    `json:"description"`
	Position       int16     `json:"position"`
	IdempotencyKey string    `json:"idempotency_key"`
	CreatedAt      time.Time `json:"created_at"`
}

type PlanOptionPhoto struct {
	PlanOptionID uuid.UUID `json:"plan_option_id"`
	ContentType  string    `json:"content_type"`
	Content      []byte    `json:"content"`
	ContentHash  []byte    `json:"content_hash"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type PlanVote struct {
	MeetingID    uuid.UUID `json:"meeting_id"`
	UserID       uuid.UUID `json:"user_id"`
	PlanOptionID uuid.UUID `json:"plan_option_id"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type PlanVoteHistory struct {
	ID                   uuid.UUID   `json:"id"`
	MeetingID            uuid.UUID   `json:"meeting_id"`
	UserID               uuid.UUID   `json:"user_id"`
	Action               string      `json:"action"`
	PreviousPlanOptionID *uuid.UUID  `json:"previous_plan_option_id"`
	PreviousPlanTitle    pgtype.Text `json:"previous_plan_title"`
	NewPlanOptionID      *uuid.UUID  `json:"new_plan_option_id"`
	NewPlanTitle         pgtype.Text `json:"new_plan_title"`
	CreatedAt            time.Time   `json:"created_at"`
}

type Poll struct {
	ID               uuid.UUID  `json:"id"`
	MeetingID        uuid.UUID  `json:"meeting_id"`
	Question         string     `json:"question"`
	ResponseMode     string     `json:"response_mode"`
	Deadline         *time.Time `json:"deadline"`
	State            string     `json:"state"`
	SelectedOptionID *uuid.UUID `json:"selected_option_id"`
	IdempotencyKey   string     `json:"idempotency_key"`
	RequestHash      []byte     `json:"request_hash"`
	CreatedAt        time.Time  `json:"created_at"`
	ClosedAt         *time.Time `json:"closed_at"`
	CreatedByUserID  uuid.UUID  `json:"created_by_user_id"`
	IsAnonymous      bool       `json:"is_anonymous"`
	AllowRevote      bool       `json:"allow_revote"`
}

type PollOption struct {
	ID       uuid.UUID `json:"id"`
	PollID   uuid.UUID `json:"poll_id"`
	Label    string    `json:"label"`
	Position int16     `json:"position"`
}

type PollVote struct {
	PollID    uuid.UUID `json:"poll_id"`
	OptionID  uuid.UUID `json:"option_id"`
	UserID    uuid.UUID `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type PollVoteHistory struct {
	ID                   uuid.UUID   `json:"id"`
	PollID               uuid.UUID   `json:"poll_id"`
	UserID               uuid.UUID   `json:"user_id"`
	Action               string      `json:"action"`
	PreviousOptionIds    []uuid.UUID `json:"previous_option_ids"`
	PreviousOptionLabels []string    `json:"previous_option_labels"`
	NewOptionIds         []uuid.UUID `json:"new_option_ids"`
	NewOptionLabels      []string    `json:"new_option_labels"`
	CreatedAt            time.Time   `json:"created_at"`
}

type RefreshSession struct {
	ID         uuid.UUID  `json:"id"`
	UserID     uuid.UUID  `json:"user_id"`
	TokenHash  []byte     `json:"token_hash"`
	ExpiresAt  time.Time  `json:"expires_at"`
	RevokedAt  *time.Time `json:"revoked_at"`
	ReplacedBy *uuid.UUID `json:"replaced_by"`
	CreatedAt  time.Time  `json:"created_at"`
}

type Requirement struct {
	ID               uuid.UUID `json:"id"`
	MeetingID        uuid.UUID `json:"meeting_id"`
	CreatedBy        uuid.UUID `json:"created_by"`
	Name             string    `json:"name"`
	RequiredQuantity int32     `json:"required_quantity"`
	Status           string    `json:"status"`
	IdempotencyKey   string    `json:"idempotency_key"`
	RequestHash      []byte    `json:"request_hash"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type RequirementClaim struct {
	MeetingID     uuid.UUID `json:"meeting_id"`
	RequirementID uuid.UUID `json:"requirement_id"`
	UserID        uuid.UUID `json:"user_id"`
	Quantity      int32     `json:"quantity"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type SchemaMigration struct {
	Version   int64     `json:"version"`
	AppliedAt time.Time `json:"applied_at"`
}

type TimeOption struct {
	ID             uuid.UUID  `json:"id"`
	MeetingID      uuid.UUID  `json:"meeting_id"`
	StartsAt       time.Time  `json:"starts_at"`
	EndsAt         *time.Time `json:"ends_at"`
	Position       int16      `json:"position"`
	IdempotencyKey string     `json:"idempotency_key"`
	CreatedAt      time.Time  `json:"created_at"`
	PlanOptionID   *uuid.UUID `json:"plan_option_id"`
}

type User struct {
	ID             uuid.UUID   `json:"id"`
	Email          string      `json:"email"`
	PasswordHash   string      `json:"password_hash"`
	DisplayName    string      `json:"display_name"`
	AvatarUrl      pgtype.Text `json:"avatar_url"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
	Nickname       string      `json:"nickname"`
	AvatarRevision pgtype.Int8 `json:"avatar_revision"`
}

type UserAvatarPhoto struct {
	UserID      uuid.UUID `json:"user_id"`
	ContentType string    `json:"content_type"`
	Content     []byte    `json:"content"`
	ContentHash []byte    `json:"content_hash"`
	UpdatedAt   time.Time `json:"updated_at"`
}
