// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notes.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countMeetingNotes = `-- name: CountMeetingNotes :one
SELECT count(*)::integer
FROM meeting_notes mn
JOIN meeting_participants mp
  ON mp.meeting_id = mn.meeting_id
 AND mp.user_id = mn.user_id
 AND mp.status = 'active'
WHERE mn.meeting_id = $1
`

func (q *Queries) CountMeetingNotes(ctx context.Context, meetingID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countMeetingNotes, meetingID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteMeetingNote = `-- name: DeleteMeetingNote :execrows
DELETE FROM meeting_notes
WHERE meeting_id = $1 AND user_id = $2
`

type DeleteMeetingNoteParams struct {
	MeetingID uuid.UUID `json:"meeting_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteMeetingNote(ctx context.Context, arg DeleteMeetingNoteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMeetingNote, arg.MeetingID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMeetingForNoteMutation = `-- name: GetMeetingForNoteMutation :one
SELECT m.state,
       CASE
           WHEN m.state = 'scheduled' AND selected_time.id IS NOT NULL
               THEN COALESCE(selected_time.ends_at, selected_time.starts_at) + interval '24 hours' <= now()
           ELSE false
       END AS archived
FROM meetings m
JOIN meeting_participants mp
  ON mp.meeting_id = m.id AND mp.user_id = $2 AND mp.status = 'active'
LEFT JOIN time_options selected_time ON selected_time.id = m.selected_time_option_id
WHERE m.id = $1
FOR UPDATE OF m
`

type GetMeetingForNoteMutationParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetMeetingForNoteMutationRow struct {
	State    string `json:"state"`
	Archived bool   `json:"archived"`
}

func (q *Queries) GetMeetingForNoteMutation(ctx context.Context, arg GetMeetingForNoteMutationParams) (GetMeetingForNoteMutationRow, error) {
	row := q.db.QueryRow(ctx, getMeetingForNoteMutation, arg.ID, arg.UserID)
	var i GetMeetingForNoteMutationRow
	err := row.Scan(&i.State, &i.Archived)
	return i, err
}

const listMeetingNotes = `-- name: ListMeetingNotes :many
SELECT mn.user_id, u.display_name, mn.text, mn.created_at, mn.updated_at
FROM meeting_notes mn
JOIN users u ON u.id = mn.user_id
JOIN meeting_participants mp
  ON mp.meeting_id = mn.meeting_id
 AND mp.user_id = mn.user_id
 AND mp.status = 'active'
WHERE mn.meeting_id = $1
ORDER BY mn.updated_at DESC, mn.user_id
LIMIT $2 OFFSET $3
`

type ListMeetingNotesParams struct {
	MeetingID uuid.UUID `json:"meeting_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

type ListMeetingNotesRow struct {
	UserID      uuid.UUID `json:"user_id"`
	DisplayName string    `json:"display_name"`
	Text        string    `json:"text"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) ListMeetingNotes(ctx context.Context, arg ListMeetingNotesParams) ([]ListMeetingNotesRow, error) {
	rows, err := q.db.Query(ctx, listMeetingNotes, arg.MeetingID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMeetingNotesRow{}
	for rows.Next() {
		var i ListMeetingNotesRow
		if err := rows.Scan(
			&i.UserID,
			&i.DisplayName,
			&i.Text,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMeetingNote = `-- name: UpsertMeetingNote :one
INSERT INTO meeting_notes (meeting_id, user_id, text)
VALUES ($1, $2, $3)
ON CONFLICT (meeting_id, user_id)
DO UPDATE SET text = EXCLUDED.text, updated_at = now()
WHERE meeting_notes.text IS DISTINCT FROM EXCLUDED.text
RETURNING true AS changed
`

type UpsertMeetingNoteParams struct {
	MeetingID uuid.UUID `json:"meeting_id"`
	UserID    uuid.UUID `json:"user_id"`
	Text      string    `json:"text"`
}

func (q *Queries) UpsertMeetingNote(ctx context.Context, arg UpsertMeetingNoteParams) (bool, error) {
	row := q.db.QueryRow(ctx, upsertMeetingNote, arg.MeetingID, arg.UserID, arg.Text)
	var changed bool
	err := row.Scan(&changed)
	return changed, err
}
