// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: polls.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const closePoll = `-- name: ClosePoll :exec
UPDATE polls
SET state = 'closed', selected_option_id = $2, closed_at = now()
WHERE id = $1
`

type ClosePollParams struct {
	ID               uuid.UUID  `json:"id"`
	SelectedOptionID *uuid.UUID `json:"selected_option_id"`
}

func (q *Queries) ClosePoll(ctx context.Context, arg ClosePollParams) error {
	_, err := q.db.Exec(ctx, closePoll, arg.ID, arg.SelectedOptionID)
	return err
}

const countMeetingPolls = `-- name: CountMeetingPolls :one
SELECT count(*)::integer
FROM polls
WHERE meeting_id = $1
`

func (q *Queries) CountMeetingPolls(ctx context.Context, meetingID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countMeetingPolls, meetingID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countPollOptionsByIDs = `-- name: CountPollOptionsByIDs :one
SELECT count(*)::integer
FROM poll_options
WHERE poll_id = $1 AND id = ANY($2::uuid[])
`

type CountPollOptionsByIDsParams struct {
	PollID  uuid.UUID   `json:"poll_id"`
	Column2 []uuid.UUID `json:"column_2"`
}

func (q *Queries) CountPollOptionsByIDs(ctx context.Context, arg CountPollOptionsByIDsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countPollOptionsByIDs, arg.PollID, arg.Column2)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countPollRespondents = `-- name: CountPollRespondents :one
SELECT count(DISTINCT user_id)::integer
FROM poll_votes
WHERE poll_id = $1
`

func (q *Queries) CountPollRespondents(ctx context.Context, pollID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countPollRespondents, pollID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countPollVoteHistory = `-- name: CountPollVoteHistory :one
SELECT count(*)::integer
FROM poll_vote_history
WHERE poll_id = $1
`

func (q *Queries) CountPollVoteHistory(ctx context.Context, pollID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countPollVoteHistory, pollID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createPoll = `-- name: CreatePoll :one
INSERT INTO polls (
    id, meeting_id, created_by_user_id, question, response_mode, deadline,
    is_anonymous, allow_revote, idempotency_key, request_hash
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, meeting_id, question, response_mode, deadline, state,
          selected_option_id, idempotency_key, request_hash, created_at, closed_at,
          created_by_user_id, is_anonymous, allow_revote
`

type CreatePollParams struct {
	ID              uuid.UUID  `json:"id"`
	MeetingID       uuid.UUID  `json:"meeting_id"`
	CreatedByUserID uuid.UUID  `json:"created_by_user_id"`
	Question        string     `json:"question"`
	ResponseMode    string     `json:"response_mode"`
	Deadline        *time.Time `json:"deadline"`
	IsAnonymous     bool       `json:"is_anonymous"`
	AllowRevote     bool       `json:"allow_revote"`
	IdempotencyKey  string     `json:"idempotency_key"`
	RequestHash     []byte     `json:"request_hash"`
}

func (q *Queries) CreatePoll(ctx context.Context, arg CreatePollParams) (Poll, error) {
	row := q.db.QueryRow(ctx, createPoll,
		arg.ID,
		arg.MeetingID,
		arg.CreatedByUserID,
		arg.Question,
		arg.ResponseMode,
		arg.Deadline,
		arg.IsAnonymous,
		arg.AllowRevote,
		arg.IdempotencyKey,
		arg.RequestHash,
	)
	var i Poll
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.Question,
		&i.ResponseMode,
		&i.Deadline,
		&i.State,
		&i.SelectedOptionID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.CreatedAt,
		&i.ClosedAt,
		&i.CreatedByUserID,
		&i.IsAnonymous,
		&i.AllowRevote,
	)
	return i, err
}

const createPollOption = `-- name: CreatePollOption :exec
INSERT INTO poll_options (id, poll_id, label, position)
VALUES ($1, $2, $3, $4)
`

type CreatePollOptionParams struct {
	ID       uuid.UUID `json:"id"`
	PollID   uuid.UUID `json:"poll_id"`
	Label    string    `json:"label"`
	Position int16     `json:"position"`
}

func (q *Queries) CreatePollOption(ctx context.Context, arg CreatePollOptionParams) error {
	_, err := q.db.Exec(ctx, createPollOption,
		arg.ID,
		arg.PollID,
		arg.Label,
		arg.Position,
	)
	return err
}

const createPollVote = `-- name: CreatePollVote :exec
INSERT INTO poll_votes (poll_id, option_id, user_id)
VALUES ($1, $2, $3)
`

type CreatePollVoteParams struct {
	PollID   uuid.UUID `json:"poll_id"`
	OptionID uuid.UUID `json:"option_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) CreatePollVote(ctx context.Context, arg CreatePollVoteParams) error {
	_, err := q.db.Exec(ctx, createPollVote, arg.PollID, arg.OptionID, arg.UserID)
	return err
}

const createPollVoteHistory = `-- name: CreatePollVoteHistory :exec
INSERT INTO poll_vote_history (
    id, poll_id, user_id, action,
    previous_option_ids, previous_option_labels,
    new_option_ids, new_option_labels
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreatePollVoteHistoryParams struct {
	ID                   uuid.UUID   `json:"id"`
	PollID               uuid.UUID   `json:"poll_id"`
	UserID               uuid.UUID   `json:"user_id"`
	Action               string      `json:"action"`
	PreviousOptionIds    []uuid.UUID `json:"previous_option_ids"`
	PreviousOptionLabels []string    `json:"previous_option_labels"`
	NewOptionIds         []uuid.UUID `json:"new_option_ids"`
	NewOptionLabels      []string    `json:"new_option_labels"`
}

func (q *Queries) CreatePollVoteHistory(ctx context.Context, arg CreatePollVoteHistoryParams) error {
	_, err := q.db.Exec(ctx, createPollVoteHistory,
		arg.ID,
		arg.PollID,
		arg.UserID,
		arg.Action,
		arg.PreviousOptionIds,
		arg.PreviousOptionLabels,
		arg.NewOptionIds,
		arg.NewOptionLabels,
	)
	return err
}

const deleteDraftPoll = `-- name: DeleteDraftPoll :execrows
DELETE FROM polls
WHERE id = $1 AND meeting_id = $2
`

type DeleteDraftPollParams struct {
	ID        uuid.UUID `json:"id"`
	MeetingID uuid.UUID `json:"meeting_id"`
}

func (q *Queries) DeleteDraftPoll(ctx context.Context, arg DeleteDraftPollParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDraftPoll, arg.ID, arg.MeetingID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserPollVotes = `-- name: DeleteUserPollVotes :exec
DELETE FROM poll_votes
WHERE poll_id = $1 AND user_id = $2
`

type DeleteUserPollVotesParams struct {
	PollID uuid.UUID `json:"poll_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteUserPollVotes(ctx context.Context, arg DeleteUserPollVotesParams) error {
	_, err := q.db.Exec(ctx, deleteUserPollVotes, arg.PollID, arg.UserID)
	return err
}

const getPollByIdempotencyKey = `-- name: GetPollByIdempotencyKey :one
SELECT id, meeting_id, question, response_mode, deadline, state,
       selected_option_id, idempotency_key, request_hash, created_at, closed_at,
       created_by_user_id, is_anonymous, allow_revote
FROM polls
WHERE meeting_id = $1 AND idempotency_key = $2
`

type GetPollByIdempotencyKeyParams struct {
	MeetingID      uuid.UUID `json:"meeting_id"`
	IdempotencyKey string    `json:"idempotency_key"`
}

func (q *Queries) GetPollByIdempotencyKey(ctx context.Context, arg GetPollByIdempotencyKeyParams) (Poll, error) {
	row := q.db.QueryRow(ctx, getPollByIdempotencyKey, arg.MeetingID, arg.IdempotencyKey)
	var i Poll
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.Question,
		&i.ResponseMode,
		&i.Deadline,
		&i.State,
		&i.SelectedOptionID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.CreatedAt,
		&i.ClosedAt,
		&i.CreatedByUserID,
		&i.IsAnonymous,
		&i.AllowRevote,
	)
	return i, err
}

const getPollForManagerForUpdate = `-- name: GetPollForManagerForUpdate :one
SELECT p.id, p.meeting_id, p.state, p.selected_option_id, m.state AS meeting_state
FROM polls p
JOIN meetings m ON m.id = p.meeting_id
WHERE p.id = $1 AND p.meeting_id = $2
  AND (m.owner_id = $3 OR p.created_by_user_id = $3)
FOR UPDATE OF p
`

type GetPollForManagerForUpdateParams struct {
	ID        uuid.UUID `json:"id"`
	MeetingID uuid.UUID `json:"meeting_id"`
	OwnerID   uuid.UUID `json:"owner_id"`
}

type GetPollForManagerForUpdateRow struct {
	ID               uuid.UUID  `json:"id"`
	MeetingID        uuid.UUID  `json:"meeting_id"`
	State            string     `json:"state"`
	SelectedOptionID *uuid.UUID `json:"selected_option_id"`
	MeetingState     string     `json:"meeting_state"`
}

func (q *Queries) GetPollForManagerForUpdate(ctx context.Context, arg GetPollForManagerForUpdateParams) (GetPollForManagerForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getPollForManagerForUpdate, arg.ID, arg.MeetingID, arg.OwnerID)
	var i GetPollForManagerForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.State,
		&i.SelectedOptionID,
		&i.MeetingState,
	)
	return i, err
}

const getPollForParticipantForUpdate = `-- name: GetPollForParticipantForUpdate :one
SELECT p.id, p.meeting_id, p.response_mode, p.deadline, p.state,
       p.allow_revote, m.state AS meeting_state
FROM polls p
JOIN meetings m ON m.id = p.meeting_id
JOIN meeting_participants mp ON mp.meeting_id = p.meeting_id
WHERE p.id = $1 AND mp.user_id = $2 AND mp.status = 'active'
FOR UPDATE OF p
`

type GetPollForParticipantForUpdateParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetPollForParticipantForUpdateRow struct {
	ID           uuid.UUID  `json:"id"`
	MeetingID    uuid.UUID  `json:"meeting_id"`
	ResponseMode string     `json:"response_mode"`
	Deadline     *time.Time `json:"deadline"`
	State        string     `json:"state"`
	AllowRevote  bool       `json:"allow_revote"`
	MeetingState string     `json:"meeting_state"`
}

func (q *Queries) GetPollForParticipantForUpdate(ctx context.Context, arg GetPollForParticipantForUpdateParams) (GetPollForParticipantForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getPollForParticipantForUpdate, arg.ID, arg.UserID)
	var i GetPollForParticipantForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.ResponseMode,
		&i.Deadline,
		&i.State,
		&i.AllowRevote,
		&i.MeetingState,
	)
	return i, err
}

const getPollMeetingID = `-- name: GetPollMeetingID :one
SELECT meeting_id
FROM polls
WHERE id = $1
`

func (q *Queries) GetPollMeetingID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getPollMeetingID, id)
	var meeting_id uuid.UUID
	err := row.Scan(&meeting_id)
	return meeting_id, err
}

const listPollOptionsByIDs = `-- name: ListPollOptionsByIDs :many
SELECT id, label, position
FROM poll_options
WHERE poll_id = $1 AND id = ANY($2::uuid[])
ORDER BY position, id
`

type ListPollOptionsByIDsParams struct {
	PollID  uuid.UUID   `json:"poll_id"`
	Column2 []uuid.UUID `json:"column_2"`
}

type ListPollOptionsByIDsRow struct {
	ID       uuid.UUID `json:"id"`
	Label    string    `json:"label"`
	Position int16     `json:"position"`
}

func (q *Queries) ListPollOptionsByIDs(ctx context.Context, arg ListPollOptionsByIDsParams) ([]ListPollOptionsByIDsRow, error) {
	rows, err := q.db.Query(ctx, listPollOptionsByIDs, arg.PollID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPollOptionsByIDsRow{}
	for rows.Next() {
		var i ListPollOptionsByIDsRow
		if err := rows.Scan(&i.ID, &i.Label, &i.Position); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPollOptionsWithResults = `-- name: ListPollOptionsWithResults :many
SELECT po.id, po.poll_id, po.label, po.position,
       count(pv.user_id)::integer AS vote_count,
       EXISTS (
           SELECT 1
           FROM poll_votes own_vote
           WHERE own_vote.poll_id = po.poll_id
             AND own_vote.option_id = po.id
             AND own_vote.user_id = $2
       ) AS selected_by_user
FROM poll_options po
LEFT JOIN poll_votes pv
  ON pv.poll_id = po.poll_id AND pv.option_id = po.id
WHERE po.poll_id = $1
GROUP BY po.id, po.poll_id, po.label, po.position
ORDER BY po.position, po.id
`

type ListPollOptionsWithResultsParams struct {
	PollID uuid.UUID `json:"poll_id"`
	UserID uuid.UUID `json:"user_id"`
}

type ListPollOptionsWithResultsRow struct {
	ID             uuid.UUID `json:"id"`
	PollID         uuid.UUID `json:"poll_id"`
	Label          string    `json:"label"`
	Position       int16     `json:"position"`
	VoteCount      int32     `json:"vote_count"`
	SelectedByUser bool      `json:"selected_by_user"`
}

func (q *Queries) ListPollOptionsWithResults(ctx context.Context, arg ListPollOptionsWithResultsParams) ([]ListPollOptionsWithResultsRow, error) {
	rows, err := q.db.Query(ctx, listPollOptionsWithResults, arg.PollID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPollOptionsWithResultsRow{}
	for rows.Next() {
		var i ListPollOptionsWithResultsRow
		if err := rows.Scan(
			&i.ID,
			&i.PollID,
			&i.Label,
			&i.Position,
			&i.VoteCount,
			&i.SelectedByUser,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPollVoteHistory = `-- name: ListPollVoteHistory :many
SELECT pvh.id, pvh.user_id, u.display_name, pvh.action,
       pvh.previous_option_ids, pvh.previous_option_labels,
       pvh.new_option_ids, pvh.new_option_labels, pvh.created_at
FROM poll_vote_history pvh
JOIN users u ON u.id = pvh.user_id
WHERE pvh.poll_id = $1
ORDER BY pvh.created_at DESC, pvh.id DESC
LIMIT $2 OFFSET $3
`

type ListPollVoteHistoryParams struct {
	PollID uuid.UUID `json:"poll_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListPollVoteHistoryRow struct {
	ID                   uuid.UUID   `json:"id"`
	UserID               uuid.UUID   `json:"user_id"`
	DisplayName          string      `json:"display_name"`
	Action               string      `json:"action"`
	PreviousOptionIds    []uuid.UUID `json:"previous_option_ids"`
	PreviousOptionLabels []string    `json:"previous_option_labels"`
	NewOptionIds         []uuid.UUID `json:"new_option_ids"`
	NewOptionLabels      []string    `json:"new_option_labels"`
	CreatedAt            time.Time   `json:"created_at"`
}

func (q *Queries) ListPollVoteHistory(ctx context.Context, arg ListPollVoteHistoryParams) ([]ListPollVoteHistoryRow, error) {
	rows, err := q.db.Query(ctx, listPollVoteHistory, arg.PollID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPollVoteHistoryRow{}
	for rows.Next() {
		var i ListPollVoteHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DisplayName,
			&i.Action,
			&i.PreviousOptionIds,
			&i.PreviousOptionLabels,
			&i.NewOptionIds,
			&i.NewOptionLabels,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPollVoters = `-- name: ListPollVoters :many
SELECT pv.option_id, u.id AS user_id, u.display_name, pv.updated_at
FROM poll_votes pv
JOIN poll_options po ON po.id = pv.option_id AND po.poll_id = pv.poll_id
JOIN users u ON u.id = pv.user_id
WHERE pv.poll_id = $1
ORDER BY po.position, lower(u.display_name), u.id
`

type ListPollVotersRow struct {
	OptionID    uuid.UUID `json:"option_id"`
	UserID      uuid.UUID `json:"user_id"`
	DisplayName string    `json:"display_name"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) ListPollVoters(ctx context.Context, pollID uuid.UUID) ([]ListPollVotersRow, error) {
	rows, err := q.db.Query(ctx, listPollVoters, pollID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPollVotersRow{}
	for rows.Next() {
		var i ListPollVotersRow
		if err := rows.Scan(
			&i.OptionID,
			&i.UserID,
			&i.DisplayName,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPollsForMeeting = `-- name: ListPollsForMeeting :many
SELECT id, meeting_id, question, response_mode, deadline, state,
       selected_option_id, idempotency_key, request_hash, created_at, closed_at,
       created_by_user_id, is_anonymous, allow_revote
FROM polls
WHERE meeting_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListPollsForMeeting(ctx context.Context, meetingID uuid.UUID) ([]Poll, error) {
	rows, err := q.db.Query(ctx, listPollsForMeeting, meetingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Poll{}
	for rows.Next() {
		var i Poll
		if err := rows.Scan(
			&i.ID,
			&i.MeetingID,
			&i.Question,
			&i.ResponseMode,
			&i.Deadline,
			&i.State,
			&i.SelectedOptionID,
			&i.IdempotencyKey,
			&i.RequestHash,
			&i.CreatedAt,
			&i.ClosedAt,
			&i.CreatedByUserID,
			&i.IsAnonymous,
			&i.AllowRevote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPollVoteOptions = `-- name: ListUserPollVoteOptions :many
SELECT po.id, po.label, po.position
FROM poll_votes pv
JOIN poll_options po ON po.poll_id = pv.poll_id AND po.id = pv.option_id
WHERE pv.poll_id = $1 AND pv.user_id = $2
ORDER BY po.position, po.id
`

type ListUserPollVoteOptionsParams struct {
	PollID uuid.UUID `json:"poll_id"`
	UserID uuid.UUID `json:"user_id"`
}

type ListUserPollVoteOptionsRow struct {
	ID       uuid.UUID `json:"id"`
	Label    string    `json:"label"`
	Position int16     `json:"position"`
}

func (q *Queries) ListUserPollVoteOptions(ctx context.Context, arg ListUserPollVoteOptionsParams) ([]ListUserPollVoteOptionsRow, error) {
	rows, err := q.db.Query(ctx, listUserPollVoteOptions, arg.PollID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserPollVoteOptionsRow{}
	for rows.Next() {
		var i ListUserPollVoteOptionsRow
		if err := rows.Scan(&i.ID, &i.Label, &i.Position); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pollOptionBelongsToPoll = `-- name: PollOptionBelongsToPoll :one
SELECT EXISTS (
    SELECT 1 FROM poll_options WHERE id = $1 AND poll_id = $2
)
`

type PollOptionBelongsToPollParams struct {
	ID     uuid.UUID `json:"id"`
	PollID uuid.UUID `json:"poll_id"`
}

func (q *Queries) PollOptionBelongsToPoll(ctx context.Context, arg PollOptionBelongsToPollParams) (bool, error) {
	row := q.db.QueryRow(ctx, pollOptionBelongsToPoll, arg.ID, arg.PollID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const pollVisibleToUser = `-- name: PollVisibleToUser :one
SELECT EXISTS (
    SELECT 1
    FROM polls p
    JOIN meeting_participants mp ON mp.meeting_id = p.meeting_id
    WHERE p.id = $1 AND mp.user_id = $2 AND mp.status = 'active'
      AND NOT p.is_anonymous
)
`

type PollVisibleToUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) PollVisibleToUser(ctx context.Context, arg PollVisibleToUserParams) (bool, error) {
	row := q.db.QueryRow(ctx, pollVisibleToUser, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
