// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: preparation.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countMeetingRequirements = `-- name: CountMeetingRequirements :one
SELECT count(*)::integer
FROM requirements
WHERE meeting_id = $1
`

func (q *Queries) CountMeetingRequirements(ctx context.Context, meetingID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countMeetingRequirements, meetingID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countRequirementStatuses = `-- name: CountRequirementStatuses :one
SELECT count(*)::integer AS total,
       count(*) FILTER (WHERE status = 'open')::integer AS open_count,
       count(*) FILTER (WHERE status = 'completed')::integer AS completed_count
FROM requirements
WHERE meeting_id = $1
`

type CountRequirementStatusesRow struct {
	Total          int32 `json:"total"`
	OpenCount      int32 `json:"open_count"`
	CompletedCount int32 `json:"completed_count"`
}

func (q *Queries) CountRequirementStatuses(ctx context.Context, meetingID uuid.UUID) (CountRequirementStatusesRow, error) {
	row := q.db.QueryRow(ctx, countRequirementStatuses, meetingID)
	var i CountRequirementStatusesRow
	err := row.Scan(&i.Total, &i.OpenCount, &i.CompletedCount)
	return i, err
}

const createRequirement = `-- name: CreateRequirement :one
INSERT INTO requirements (
    id, meeting_id, created_by, name, required_quantity, idempotency_key, request_hash
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, meeting_id, created_by, name, required_quantity, status,
          idempotency_key, request_hash, created_at, updated_at
`

type CreateRequirementParams struct {
	ID               uuid.UUID `json:"id"`
	MeetingID        uuid.UUID `json:"meeting_id"`
	CreatedBy        uuid.UUID `json:"created_by"`
	Name             string    `json:"name"`
	RequiredQuantity int32     `json:"required_quantity"`
	IdempotencyKey   string    `json:"idempotency_key"`
	RequestHash      []byte    `json:"request_hash"`
}

func (q *Queries) CreateRequirement(ctx context.Context, arg CreateRequirementParams) (Requirement, error) {
	row := q.db.QueryRow(ctx, createRequirement,
		arg.ID,
		arg.MeetingID,
		arg.CreatedBy,
		arg.Name,
		arg.RequiredQuantity,
		arg.IdempotencyKey,
		arg.RequestHash,
	)
	var i Requirement
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.CreatedBy,
		&i.Name,
		&i.RequiredQuantity,
		&i.Status,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRequirement = `-- name: DeleteRequirement :execrows
DELETE FROM requirements
WHERE meeting_id = $1 AND id = $2
`

type DeleteRequirementParams struct {
	MeetingID uuid.UUID `json:"meeting_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) DeleteRequirement(ctx context.Context, arg DeleteRequirementParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRequirement, arg.MeetingID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRequirementClaim = `-- name: DeleteRequirementClaim :execrows
DELETE FROM requirement_claims
WHERE requirement_id = $1 AND user_id = $2
`

type DeleteRequirementClaimParams struct {
	RequirementID uuid.UUID `json:"requirement_id"`
	UserID        uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteRequirementClaim(ctx context.Context, arg DeleteRequirementClaimParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRequirementClaim, arg.RequirementID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRequirementByIdempotencyKey = `-- name: GetRequirementByIdempotencyKey :one
SELECT id, meeting_id, created_by, name, required_quantity, status,
       idempotency_key, request_hash, created_at, updated_at
FROM requirements
WHERE meeting_id = $1 AND idempotency_key = $2
`

type GetRequirementByIdempotencyKeyParams struct {
	MeetingID      uuid.UUID `json:"meeting_id"`
	IdempotencyKey string    `json:"idempotency_key"`
}

func (q *Queries) GetRequirementByIdempotencyKey(ctx context.Context, arg GetRequirementByIdempotencyKeyParams) (Requirement, error) {
	row := q.db.QueryRow(ctx, getRequirementByIdempotencyKey, arg.MeetingID, arg.IdempotencyKey)
	var i Requirement
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.CreatedBy,
		&i.Name,
		&i.RequiredQuantity,
		&i.Status,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRequirementClaim = `-- name: GetRequirementClaim :one
SELECT quantity
FROM requirement_claims
WHERE requirement_id = $1 AND user_id = $2
`

type GetRequirementClaimParams struct {
	RequirementID uuid.UUID `json:"requirement_id"`
	UserID        uuid.UUID `json:"user_id"`
}

func (q *Queries) GetRequirementClaim(ctx context.Context, arg GetRequirementClaimParams) (int32, error) {
	row := q.db.QueryRow(ctx, getRequirementClaim, arg.RequirementID, arg.UserID)
	var quantity int32
	err := row.Scan(&quantity)
	return quantity, err
}

const getRequirementForUpdate = `-- name: GetRequirementForUpdate :one
SELECT id, meeting_id, name, required_quantity, status, created_at, updated_at
FROM requirements
WHERE meeting_id = $1 AND id = $2
FOR UPDATE
`

type GetRequirementForUpdateParams struct {
	MeetingID uuid.UUID `json:"meeting_id"`
	ID        uuid.UUID `json:"id"`
}

type GetRequirementForUpdateRow struct {
	ID               uuid.UUID `json:"id"`
	MeetingID        uuid.UUID `json:"meeting_id"`
	Name             string    `json:"name"`
	RequiredQuantity int32     `json:"required_quantity"`
	Status           string    `json:"status"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

func (q *Queries) GetRequirementForUpdate(ctx context.Context, arg GetRequirementForUpdateParams) (GetRequirementForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getRequirementForUpdate, arg.MeetingID, arg.ID)
	var i GetRequirementForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.Name,
		&i.RequiredQuantity,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRequirementClaims = `-- name: ListRequirementClaims :many
SELECT c.requirement_id, c.user_id, u.display_name, c.quantity, c.updated_at
FROM requirement_claims c
JOIN users u ON u.id = c.user_id
WHERE c.meeting_id = $1
ORDER BY c.requirement_id, c.created_at, c.user_id
`

type ListRequirementClaimsRow struct {
	RequirementID uuid.UUID `json:"requirement_id"`
	UserID        uuid.UUID `json:"user_id"`
	DisplayName   string    `json:"display_name"`
	Quantity      int32     `json:"quantity"`
	UpdatedAt     time.Time `json:"updated_at"`
}

func (q *Queries) ListRequirementClaims(ctx context.Context, meetingID uuid.UUID) ([]ListRequirementClaimsRow, error) {
	rows, err := q.db.Query(ctx, listRequirementClaims, meetingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRequirementClaimsRow{}
	for rows.Next() {
		var i ListRequirementClaimsRow
		if err := rows.Scan(
			&i.RequirementID,
			&i.UserID,
			&i.DisplayName,
			&i.Quantity,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequirements = `-- name: ListRequirements :many
SELECT r.id, r.name, r.required_quantity,
       COALESCE(sum(c.quantity), 0)::integer AS claimed_quantity,
       r.status,
       COALESCE(mine.quantity, 0)::integer AS my_quantity,
       r.created_at, r.updated_at
FROM requirements r
LEFT JOIN requirement_claims c
  ON c.meeting_id = r.meeting_id AND c.requirement_id = r.id
LEFT JOIN requirement_claims mine
  ON mine.meeting_id = r.meeting_id
 AND mine.requirement_id = r.id
 AND mine.user_id = $2
WHERE r.meeting_id = $1
GROUP BY r.id, mine.quantity
ORDER BY (r.status = 'completed'), r.created_at, r.id
LIMIT $3 OFFSET $4
`

type ListRequirementsParams struct {
	MeetingID uuid.UUID `json:"meeting_id"`
	UserID    uuid.UUID `json:"user_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

type ListRequirementsRow struct {
	ID               uuid.UUID `json:"id"`
	Name             string    `json:"name"`
	RequiredQuantity int32     `json:"required_quantity"`
	ClaimedQuantity  int32     `json:"claimed_quantity"`
	Status           string    `json:"status"`
	MyQuantity       int32     `json:"my_quantity"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

func (q *Queries) ListRequirements(ctx context.Context, arg ListRequirementsParams) ([]ListRequirementsRow, error) {
	rows, err := q.db.Query(ctx, listRequirements,
		arg.MeetingID,
		arg.UserID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRequirementsRow{}
	for rows.Next() {
		var i ListRequirementsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RequiredQuantity,
			&i.ClaimedQuantity,
			&i.Status,
			&i.MyQuantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRequirementStatus = `-- name: SetRequirementStatus :exec
UPDATE requirements
SET status = $3, updated_at = now()
WHERE meeting_id = $1 AND id = $2
`

type SetRequirementStatusParams struct {
	MeetingID uuid.UUID `json:"meeting_id"`
	ID        uuid.UUID `json:"id"`
	Status    string    `json:"status"`
}

func (q *Queries) SetRequirementStatus(ctx context.Context, arg SetRequirementStatusParams) error {
	_, err := q.db.Exec(ctx, setRequirementStatus, arg.MeetingID, arg.ID, arg.Status)
	return err
}

const sumRequirementClaims = `-- name: SumRequirementClaims :one
SELECT COALESCE(sum(quantity), 0)::integer
FROM requirement_claims
WHERE requirement_id = $1
`

func (q *Queries) SumRequirementClaims(ctx context.Context, requirementID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, sumRequirementClaims, requirementID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const updateRequirement = `-- name: UpdateRequirement :execrows
UPDATE requirements
SET name = $3, required_quantity = $4, updated_at = now()
WHERE meeting_id = $1 AND id = $2
`

type UpdateRequirementParams struct {
	MeetingID        uuid.UUID `json:"meeting_id"`
	ID               uuid.UUID `json:"id"`
	Name             string    `json:"name"`
	RequiredQuantity int32     `json:"required_quantity"`
}

func (q *Queries) UpdateRequirement(ctx context.Context, arg UpdateRequirementParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRequirement,
		arg.MeetingID,
		arg.ID,
		arg.Name,
		arg.RequiredQuantity,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertRequirementClaim = `-- name: UpsertRequirementClaim :exec
INSERT INTO requirement_claims (meeting_id, requirement_id, user_id, quantity)
VALUES ($1, $2, $3, $4)
ON CONFLICT (requirement_id, user_id)
DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now()
`

type UpsertRequirementClaimParams struct {
	MeetingID     uuid.UUID `json:"meeting_id"`
	RequirementID uuid.UUID `json:"requirement_id"`
	UserID        uuid.UUID `json:"user_id"`
	Quantity      int32     `json:"quantity"`
}

func (q *Queries) UpsertRequirementClaim(ctx context.Context, arg UpsertRequirementClaimParams) error {
	_, err := q.db.Exec(ctx, upsertRequirementClaim,
		arg.MeetingID,
		arg.RequirementID,
		arg.UserID,
		arg.Quantity,
	)
	return err
}
