// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	AcceptFriendRequest(ctx context.Context, arg AcceptFriendRequestParams) (Friendship, error)
	AddMeetingParticipant(ctx context.Context, arg AddMeetingParticipantParams) error
	CancelMeeting(ctx context.Context, id uuid.UUID) (CancelMeetingRow, error)
	ClosePoll(ctx context.Context, arg ClosePollParams) error
	CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) error
	CompleteMeeting(ctx context.Context, id uuid.UUID) (CompleteMeetingRow, error)
	CountActiveMeetingParticipants(ctx context.Context, meetingID uuid.UUID) (int32, error)
	CountAttendanceParticipants(ctx context.Context, meetingID uuid.UUID) (CountAttendanceParticipantsRow, error)
	CountFriends(ctx context.Context, requesterID uuid.UUID) (int64, error)
	CountIncomingFriendRequests(ctx context.Context, addresseeID uuid.UUID) (int64, error)
	CountMeetingNotes(ctx context.Context, meetingID uuid.UUID) (int32, error)
	CountMeetingPolls(ctx context.Context, meetingID uuid.UUID) (int32, error)
	CountMeetingRequirements(ctx context.Context, meetingID uuid.UUID) (int32, error)
	CountOpenRequirements(ctx context.Context, meetingID uuid.UUID) (int32, error)
	CountOutgoingFriendRequests(ctx context.Context, requesterID uuid.UUID) (int64, error)
	CountPlanOptions(ctx context.Context, meetingID uuid.UUID) (int32, error)
	CountPlanVoteHistory(ctx context.Context, meetingID uuid.UUID) (int32, error)
	CountPollOptionsByIDs(ctx context.Context, arg CountPollOptionsByIDsParams) (int32, error)
	CountPollRespondents(ctx context.Context, pollID uuid.UUID) (int32, error)
	CountPollVoteHistory(ctx context.Context, pollID uuid.UUID) (int32, error)
	CountRequirementStatuses(ctx context.Context, meetingID uuid.UUID) (CountRequirementStatusesRow, error)
	CountTimeOptions(ctx context.Context, meetingID uuid.UUID) (int32, error)
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error)
	CreateMeeting(ctx context.Context, arg CreateMeetingParams) (CreateMeetingRow, error)
	CreatePlanOption(ctx context.Context, arg CreatePlanOptionParams) (PlanOption, error)
	CreatePlanVoteHistory(ctx context.Context, arg CreatePlanVoteHistoryParams) error
	CreatePoll(ctx context.Context, arg CreatePollParams) (Poll, error)
	CreatePollOption(ctx context.Context, arg CreatePollOptionParams) error
	CreatePollVote(ctx context.Context, arg CreatePollVoteParams) error
	CreatePollVoteHistory(ctx context.Context, arg CreatePollVoteHistoryParams) error
	CreateRefreshSession(ctx context.Context, arg CreateRefreshSessionParams) error
	CreateRequirement(ctx context.Context, arg CreateRequirementParams) (Requirement, error)
	CreateTimeOption(ctx context.Context, arg CreateTimeOptionParams) (TimeOption, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAcceptedFriendship(ctx context.Context, arg DeleteAcceptedFriendshipParams) (int64, error)
	DeleteAttendanceResponse(ctx context.Context, arg DeleteAttendanceResponseParams) (int64, error)
	DeleteAvailabilityVote(ctx context.Context, arg DeleteAvailabilityVoteParams) (int64, error)
	DeleteDraftPoll(ctx context.Context, arg DeleteDraftPollParams) (int64, error)
	DeleteMeetingNote(ctx context.Context, arg DeleteMeetingNoteParams) (int64, error)
	DeletePendingFriendRequest(ctx context.Context, arg DeletePendingFriendRequestParams) (int64, error)
	DeletePlanOption(ctx context.Context, arg DeletePlanOptionParams) (int64, error)
	DeletePlanVote(ctx context.Context, arg DeletePlanVoteParams) (int64, error)
	DeleteRequirement(ctx context.Context, arg DeleteRequirementParams) (int64, error)
	DeleteRequirementClaim(ctx context.Context, arg DeleteRequirementClaimParams) (int64, error)
	DeleteTimeOption(ctx context.Context, arg DeleteTimeOptionParams) (int64, error)
	DeleteUserPollVotes(ctx context.Context, arg DeleteUserPollVotesParams) error
	GetActiveInvitationExpiry(ctx context.Context, meetingID uuid.UUID) (time.Time, error)
	GetAttendanceResponse(ctx context.Context, arg GetAttendanceResponseParams) (string, error)
	GetCurrentPlanVote(ctx context.Context, arg GetCurrentPlanVoteParams) (GetCurrentPlanVoteRow, error)
	GetFriendshipByIDForUpdate(ctx context.Context, id uuid.UUID) (Friendship, error)
	GetFriendshipByPair(ctx context.Context, arg GetFriendshipByPairParams) (Friendship, error)
	GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error)
	GetInvitationByIdempotencyKey(ctx context.Context, arg GetInvitationByIdempotencyKeyParams) (Invitation, error)
	GetInvitationMeetingByHash(ctx context.Context, secretHash []byte) (uuid.UUID, error)
	GetMeetingCancellationForOwnerForUpdate(ctx context.Context, arg GetMeetingCancellationForOwnerForUpdateParams) (GetMeetingCancellationForOwnerForUpdateRow, error)
	GetMeetingCompletionForOwnerForUpdate(ctx context.Context, arg GetMeetingCompletionForOwnerForUpdateParams) (GetMeetingCompletionForOwnerForUpdateRow, error)
	GetMeetingDecisionForOwnerForUpdate(ctx context.Context, arg GetMeetingDecisionForOwnerForUpdateParams) (GetMeetingDecisionForOwnerForUpdateRow, error)
	GetMeetingForNoteMutation(ctx context.Context, arg GetMeetingForNoteMutationParams) (GetMeetingForNoteMutationRow, error)
	GetMeetingForOwnerForUpdate(ctx context.Context, arg GetMeetingForOwnerForUpdateParams) (GetMeetingForOwnerForUpdateRow, error)
	GetMeetingForUser(ctx context.Context, arg GetMeetingForUserParams) (GetMeetingForUserRow, error)
	GetPlanOptionByIdempotencyKey(ctx context.Context, arg GetPlanOptionByIdempotencyKeyParams) (PlanOption, error)
	GetPlanOptionForVote(ctx context.Context, arg GetPlanOptionForVoteParams) (GetPlanOptionForVoteRow, error)
	GetPollByIdempotencyKey(ctx context.Context, arg GetPollByIdempotencyKeyParams) (Poll, error)
	GetPollForManagerForUpdate(ctx context.Context, arg GetPollForManagerForUpdateParams) (GetPollForManagerForUpdateRow, error)
	GetPollForParticipantForUpdate(ctx context.Context, arg GetPollForParticipantForUpdateParams) (GetPollForParticipantForUpdateRow, error)
	GetPollMeetingID(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	GetRefreshSessionForUpdate(ctx context.Context, tokenHash []byte) (RefreshSession, error)
	GetRequirementByIdempotencyKey(ctx context.Context, arg GetRequirementByIdempotencyKeyParams) (Requirement, error)
	GetRequirementClaim(ctx context.Context, arg GetRequirementClaimParams) (int32, error)
	GetRequirementForUpdate(ctx context.Context, arg GetRequirementForUpdateParams) (GetRequirementForUpdateRow, error)
	GetTimeOptionByIdempotencyKey(ctx context.Context, arg GetTimeOptionByIdempotencyKeyParams) (TimeOption, error)
	GetTimeOptionForDecision(ctx context.Context, arg GetTimeOptionForDecisionParams) (GetTimeOptionForDecisionRow, error)
	GetTimeOptionMeetingID(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetValidInvitationForUpdate(ctx context.Context, arg GetValidInvitationForUpdateParams) (Invitation, error)
	InsertFriendRequest(ctx context.Context, arg InsertFriendRequestParams) (Friendship, error)
	JoinMeeting(ctx context.Context, arg JoinMeetingParams) (int64, error)
	ListAttendanceParticipants(ctx context.Context, arg ListAttendanceParticipantsParams) ([]ListAttendanceParticipantsRow, error)
	ListAvailabilityVotes(ctx context.Context, meetingID uuid.UUID) ([]ListAvailabilityVotesRow, error)
	ListFriends(ctx context.Context, arg ListFriendsParams) ([]ListFriendsRow, error)
	ListIncomingFriendRequests(ctx context.Context, arg ListIncomingFriendRequestsParams) ([]ListIncomingFriendRequestsRow, error)
	ListMeetingNotes(ctx context.Context, arg ListMeetingNotesParams) ([]ListMeetingNotesRow, error)
	ListMeetingParticipants(ctx context.Context, meetingID uuid.UUID) ([]ListMeetingParticipantsRow, error)
	ListMeetingsForUser(ctx context.Context, arg ListMeetingsForUserParams) ([]ListMeetingsForUserRow, error)
	ListOutgoingFriendRequests(ctx context.Context, arg ListOutgoingFriendRequestsParams) ([]ListOutgoingFriendRequestsRow, error)
	ListPlanOptions(ctx context.Context, meetingID uuid.UUID) ([]PlanOption, error)
	ListPlanVoteHistory(ctx context.Context, arg ListPlanVoteHistoryParams) ([]ListPlanVoteHistoryRow, error)
	ListPlanVoteOptions(ctx context.Context, arg ListPlanVoteOptionsParams) ([]ListPlanVoteOptionsRow, error)
	ListPlanVoteResponses(ctx context.Context, meetingID uuid.UUID) ([]ListPlanVoteResponsesRow, error)
	ListPollOptionsByIDs(ctx context.Context, arg ListPollOptionsByIDsParams) ([]ListPollOptionsByIDsRow, error)
	ListPollOptionsWithResults(ctx context.Context, arg ListPollOptionsWithResultsParams) ([]ListPollOptionsWithResultsRow, error)
	ListPollVoteHistory(ctx context.Context, arg ListPollVoteHistoryParams) ([]ListPollVoteHistoryRow, error)
	ListPollVoters(ctx context.Context, pollID uuid.UUID) ([]ListPollVotersRow, error)
	ListPollsForMeeting(ctx context.Context, meetingID uuid.UUID) ([]Poll, error)
	ListRequirementClaims(ctx context.Context, meetingID uuid.UUID) ([]ListRequirementClaimsRow, error)
	ListRequirements(ctx context.Context, arg ListRequirementsParams) ([]ListRequirementsRow, error)
	ListTimeOptions(ctx context.Context, meetingID uuid.UUID) ([]TimeOption, error)
	ListUserPollVoteOptions(ctx context.Context, arg ListUserPollVoteOptionsParams) ([]ListUserPollVoteOptionsRow, error)
	LockMeetingByID(ctx context.Context, id uuid.UUID) (LockMeetingByIDRow, error)
	NextPlanOptionPosition(ctx context.Context, meetingID uuid.UUID) (int16, error)
	NextTimeOptionPosition(ctx context.Context, meetingID uuid.UUID) (int16, error)
	OpenMeetingCollection(ctx context.Context, id uuid.UUID) error
	PlanOptionBelongsToMeeting(ctx context.Context, arg PlanOptionBelongsToMeetingParams) (bool, error)
	PollOptionBelongsToPoll(ctx context.Context, arg PollOptionBelongsToPollParams) (bool, error)
	PollVisibleToUser(ctx context.Context, arg PollVisibleToUserParams) (bool, error)
	ReserveIdempotencyKey(ctx context.Context, arg ReserveIdempotencyKeyParams) (int64, error)
	RevokeActiveInvitations(ctx context.Context, meetingID uuid.UUID) (int64, error)
	RevokeRefreshSession(ctx context.Context, tokenHash []byte) (int64, error)
	RotateRefreshSession(ctx context.Context, arg RotateRefreshSessionParams) (int64, error)
	ScheduleMeeting(ctx context.Context, arg ScheduleMeetingParams) error
	SearchUsersByNickname(ctx context.Context, arg SearchUsersByNicknameParams) ([]SearchUsersByNicknameRow, error)
	SetRequirementStatus(ctx context.Context, arg SetRequirementStatusParams) error
	SumRequirementClaims(ctx context.Context, requirementID uuid.UUID) (int32, error)
	TouchMeeting(ctx context.Context, id uuid.UUID) error
	UpdateDraftMeeting(ctx context.Context, arg UpdateDraftMeetingParams) (UpdateDraftMeetingRow, error)
	UpdatePlanOption(ctx context.Context, arg UpdatePlanOptionParams) (PlanOption, error)
	UpdateRequirement(ctx context.Context, arg UpdateRequirementParams) (int64, error)
	UpdateTimeOption(ctx context.Context, arg UpdateTimeOptionParams) (TimeOption, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpsertAttendanceResponse(ctx context.Context, arg UpsertAttendanceResponseParams) error
	UpsertAvailabilityVote(ctx context.Context, arg UpsertAvailabilityVoteParams) (int64, error)
	UpsertMeetingNote(ctx context.Context, arg UpsertMeetingNoteParams) (bool, error)
	UpsertPlanVote(ctx context.Context, arg UpsertPlanVoteParams) error
	UpsertRequirementClaim(ctx context.Context, arg UpsertRequirementClaimParams) error
}

var _ Querier = (*Queries)(nil)
