// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: setup.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const cancelMeeting = `-- name: CancelMeeting :one
UPDATE meetings
SET state = 'cancelled', version = version + 1, updated_at = now()
WHERE id = $1
RETURNING version, updated_at
`

type CancelMeetingRow struct {
	Version   int64     `json:"version"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CancelMeeting(ctx context.Context, id uuid.UUID) (CancelMeetingRow, error) {
	row := q.db.QueryRow(ctx, cancelMeeting, id)
	var i CancelMeetingRow
	err := row.Scan(&i.Version, &i.UpdatedAt)
	return i, err
}

const completeMeeting = `-- name: CompleteMeeting :one
UPDATE meetings
SET state = 'completed', version = version + 1, updated_at = now()
WHERE id = $1
RETURNING version, updated_at
`

type CompleteMeetingRow struct {
	Version   int64     `json:"version"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CompleteMeeting(ctx context.Context, id uuid.UUID) (CompleteMeetingRow, error) {
	row := q.db.QueryRow(ctx, completeMeeting, id)
	var i CompleteMeetingRow
	err := row.Scan(&i.Version, &i.UpdatedAt)
	return i, err
}

const countOpenRequirements = `-- name: CountOpenRequirements :one
SELECT count(*)::integer
FROM requirements
WHERE meeting_id = $1 AND status <> 'completed'
`

func (q *Queries) CountOpenRequirements(ctx context.Context, meetingID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countOpenRequirements, meetingID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countPlanOptions = `-- name: CountPlanOptions :one
SELECT count(*)::integer
FROM plan_options
WHERE meeting_id = $1
`

func (q *Queries) CountPlanOptions(ctx context.Context, meetingID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countPlanOptions, meetingID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countTimeOptions = `-- name: CountTimeOptions :one
SELECT count(*)::integer
FROM time_options
WHERE meeting_id = $1
`

func (q *Queries) CountTimeOptions(ctx context.Context, meetingID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countTimeOptions, meetingID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations (
    id, meeting_id, created_by, secret_hash, idempotency_key, expires_at
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (meeting_id, idempotency_key) DO NOTHING
RETURNING id, meeting_id, created_by, secret_hash, idempotency_key, default_role,
          expires_at, revoked_at, created_at
`

type CreateInvitationParams struct {
	ID             uuid.UUID `json:"id"`
	MeetingID      uuid.UUID `json:"meeting_id"`
	CreatedBy      uuid.UUID `json:"created_by"`
	SecretHash     []byte    `json:"secret_hash"`
	IdempotencyKey string    `json:"idempotency_key"`
	ExpiresAt      time.Time `json:"expires_at"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.ID,
		arg.MeetingID,
		arg.CreatedBy,
		arg.SecretHash,
		arg.IdempotencyKey,
		arg.ExpiresAt,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.CreatedBy,
		&i.SecretHash,
		&i.IdempotencyKey,
		&i.DefaultRole,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createPlanOption = `-- name: CreatePlanOption :one
INSERT INTO plan_options (
    id, meeting_id, title, description, position, idempotency_key
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (meeting_id, idempotency_key) DO NOTHING
RETURNING id, meeting_id, title, description, position, idempotency_key, created_at
`

type CreatePlanOptionParams struct {
	ID             uuid.UUID `json:"id"`
	MeetingID      uuid.UUID `json:"meeting_id"`
	Title          string    `json:"title"`
	Description    string    `json:"description"`
	Position       int16     `json:"position"`
	IdempotencyKey string    `json:"idempotency_key"`
}

func (q *Queries) CreatePlanOption(ctx context.Context, arg CreatePlanOptionParams) (PlanOption, error) {
	row := q.db.QueryRow(ctx, createPlanOption,
		arg.ID,
		arg.MeetingID,
		arg.Title,
		arg.Description,
		arg.Position,
		arg.IdempotencyKey,
	)
	var i PlanOption
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const createTimeOption = `-- name: CreateTimeOption :one
INSERT INTO time_options (
    id, meeting_id, plan_option_id, starts_at, ends_at, position, idempotency_key
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (meeting_id, idempotency_key) DO NOTHING
RETURNING id, meeting_id, starts_at, ends_at, position, idempotency_key, created_at, plan_option_id
`

type CreateTimeOptionParams struct {
	ID             uuid.UUID  `json:"id"`
	MeetingID      uuid.UUID  `json:"meeting_id"`
	PlanOptionID   *uuid.UUID `json:"plan_option_id"`
	StartsAt       time.Time  `json:"starts_at"`
	EndsAt         *time.Time `json:"ends_at"`
	Position       int16      `json:"position"`
	IdempotencyKey string     `json:"idempotency_key"`
}

func (q *Queries) CreateTimeOption(ctx context.Context, arg CreateTimeOptionParams) (TimeOption, error) {
	row := q.db.QueryRow(ctx, createTimeOption,
		arg.ID,
		arg.MeetingID,
		arg.PlanOptionID,
		arg.StartsAt,
		arg.EndsAt,
		arg.Position,
		arg.IdempotencyKey,
	)
	var i TimeOption
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.StartsAt,
		&i.EndsAt,
		&i.Position,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.PlanOptionID,
	)
	return i, err
}

const deletePlanOption = `-- name: DeletePlanOption :execrows
DELETE FROM plan_options
WHERE id = $1 AND meeting_id = $2
`

type DeletePlanOptionParams struct {
	ID        uuid.UUID `json:"id"`
	MeetingID uuid.UUID `json:"meeting_id"`
}

func (q *Queries) DeletePlanOption(ctx context.Context, arg DeletePlanOptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePlanOption, arg.ID, arg.MeetingID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTimeOption = `-- name: DeleteTimeOption :execrows
DELETE FROM time_options
WHERE id = $1 AND meeting_id = $2
`

type DeleteTimeOptionParams struct {
	ID        uuid.UUID `json:"id"`
	MeetingID uuid.UUID `json:"meeting_id"`
}

func (q *Queries) DeleteTimeOption(ctx context.Context, arg DeleteTimeOptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTimeOption, arg.ID, arg.MeetingID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveInvitationExpiry = `-- name: GetActiveInvitationExpiry :one
SELECT expires_at
FROM invitations
WHERE meeting_id = $1 AND revoked_at IS NULL AND expires_at > now()
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveInvitationExpiry(ctx context.Context, meetingID uuid.UUID) (time.Time, error) {
	row := q.db.QueryRow(ctx, getActiveInvitationExpiry, meetingID)
	var expires_at time.Time
	err := row.Scan(&expires_at)
	return expires_at, err
}

const getInvitationByIdempotencyKey = `-- name: GetInvitationByIdempotencyKey :one
SELECT id, meeting_id, created_by, secret_hash, idempotency_key, default_role,
       expires_at, revoked_at, created_at
FROM invitations
WHERE meeting_id = $1 AND idempotency_key = $2
`

type GetInvitationByIdempotencyKeyParams struct {
	MeetingID      uuid.UUID `json:"meeting_id"`
	IdempotencyKey string    `json:"idempotency_key"`
}

func (q *Queries) GetInvitationByIdempotencyKey(ctx context.Context, arg GetInvitationByIdempotencyKeyParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByIdempotencyKey, arg.MeetingID, arg.IdempotencyKey)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.CreatedBy,
		&i.SecretHash,
		&i.IdempotencyKey,
		&i.DefaultRole,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInvitationMeetingByHash = `-- name: GetInvitationMeetingByHash :one
SELECT meeting_id
FROM invitations
WHERE secret_hash = $1
`

func (q *Queries) GetInvitationMeetingByHash(ctx context.Context, secretHash []byte) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getInvitationMeetingByHash, secretHash)
	var meeting_id uuid.UUID
	err := row.Scan(&meeting_id)
	return meeting_id, err
}

const getMeetingCancellationForOwnerForUpdate = `-- name: GetMeetingCancellationForOwnerForUpdate :one
SELECT state, version, updated_at
FROM meetings
WHERE id = $1 AND owner_id = $2
FOR UPDATE
`

type GetMeetingCancellationForOwnerForUpdateParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"owner_id"`
}

type GetMeetingCancellationForOwnerForUpdateRow struct {
	State     string    `json:"state"`
	Version   int64     `json:"version"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) GetMeetingCancellationForOwnerForUpdate(ctx context.Context, arg GetMeetingCancellationForOwnerForUpdateParams) (GetMeetingCancellationForOwnerForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getMeetingCancellationForOwnerForUpdate, arg.ID, arg.OwnerID)
	var i GetMeetingCancellationForOwnerForUpdateRow
	err := row.Scan(&i.State, &i.Version, &i.UpdatedAt)
	return i, err
}

const getMeetingCompletionForOwnerForUpdate = `-- name: GetMeetingCompletionForOwnerForUpdate :one
SELECT state, version, updated_at
FROM meetings
WHERE id = $1 AND owner_id = $2
FOR UPDATE
`

type GetMeetingCompletionForOwnerForUpdateParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"owner_id"`
}

type GetMeetingCompletionForOwnerForUpdateRow struct {
	State     string    `json:"state"`
	Version   int64     `json:"version"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) GetMeetingCompletionForOwnerForUpdate(ctx context.Context, arg GetMeetingCompletionForOwnerForUpdateParams) (GetMeetingCompletionForOwnerForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getMeetingCompletionForOwnerForUpdate, arg.ID, arg.OwnerID)
	var i GetMeetingCompletionForOwnerForUpdateRow
	err := row.Scan(&i.State, &i.Version, &i.UpdatedAt)
	return i, err
}

const getMeetingForOwnerForUpdate = `-- name: GetMeetingForOwnerForUpdate :one
SELECT m.id, m.state, m.coordination_mode, m.version,
       CASE
           WHEN m.state = 'scheduled' AND selected_time.id IS NOT NULL
               THEN COALESCE(selected_time.ends_at, selected_time.starts_at) + interval '24 hours' <= now()
           ELSE false
       END AS archived
FROM meetings m
LEFT JOIN time_options selected_time ON selected_time.id = m.selected_time_option_id
WHERE m.id = $1 AND m.owner_id = $2
FOR UPDATE OF m
`

type GetMeetingForOwnerForUpdateParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"owner_id"`
}

type GetMeetingForOwnerForUpdateRow struct {
	ID               uuid.UUID `json:"id"`
	State            string    `json:"state"`
	CoordinationMode string    `json:"coordination_mode"`
	Version          int64     `json:"version"`
	Archived         bool      `json:"archived"`
}

func (q *Queries) GetMeetingForOwnerForUpdate(ctx context.Context, arg GetMeetingForOwnerForUpdateParams) (GetMeetingForOwnerForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getMeetingForOwnerForUpdate, arg.ID, arg.OwnerID)
	var i GetMeetingForOwnerForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.CoordinationMode,
		&i.Version,
		&i.Archived,
	)
	return i, err
}

const getPlanOptionByIdempotencyKey = `-- name: GetPlanOptionByIdempotencyKey :one
SELECT id, meeting_id, title, description, position, idempotency_key, created_at
FROM plan_options
WHERE meeting_id = $1 AND idempotency_key = $2
`

type GetPlanOptionByIdempotencyKeyParams struct {
	MeetingID      uuid.UUID `json:"meeting_id"`
	IdempotencyKey string    `json:"idempotency_key"`
}

func (q *Queries) GetPlanOptionByIdempotencyKey(ctx context.Context, arg GetPlanOptionByIdempotencyKeyParams) (PlanOption, error) {
	row := q.db.QueryRow(ctx, getPlanOptionByIdempotencyKey, arg.MeetingID, arg.IdempotencyKey)
	var i PlanOption
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const getTimeOptionByIdempotencyKey = `-- name: GetTimeOptionByIdempotencyKey :one
SELECT id, meeting_id, starts_at, ends_at, position, idempotency_key, created_at, plan_option_id
FROM time_options
WHERE meeting_id = $1 AND idempotency_key = $2
`

type GetTimeOptionByIdempotencyKeyParams struct {
	MeetingID      uuid.UUID `json:"meeting_id"`
	IdempotencyKey string    `json:"idempotency_key"`
}

func (q *Queries) GetTimeOptionByIdempotencyKey(ctx context.Context, arg GetTimeOptionByIdempotencyKeyParams) (TimeOption, error) {
	row := q.db.QueryRow(ctx, getTimeOptionByIdempotencyKey, arg.MeetingID, arg.IdempotencyKey)
	var i TimeOption
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.StartsAt,
		&i.EndsAt,
		&i.Position,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.PlanOptionID,
	)
	return i, err
}

const getValidInvitationForUpdate = `-- name: GetValidInvitationForUpdate :one
SELECT id, meeting_id, created_by, secret_hash, idempotency_key, default_role,
       expires_at, revoked_at, created_at
FROM invitations
WHERE meeting_id = $1
  AND secret_hash = $2
  AND revoked_at IS NULL
  AND expires_at > now()
FOR UPDATE
`

type GetValidInvitationForUpdateParams struct {
	MeetingID  uuid.UUID `json:"meeting_id"`
	SecretHash []byte    `json:"secret_hash"`
}

func (q *Queries) GetValidInvitationForUpdate(ctx context.Context, arg GetValidInvitationForUpdateParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, getValidInvitationForUpdate, arg.MeetingID, arg.SecretHash)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.CreatedBy,
		&i.SecretHash,
		&i.IdempotencyKey,
		&i.DefaultRole,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const joinMeeting = `-- name: JoinMeeting :execrows
INSERT INTO meeting_participants (meeting_id, user_id, role, status)
VALUES ($1, $2, 'participant', 'active')
ON CONFLICT (meeting_id, user_id)
DO UPDATE SET status = 'active'
WHERE meeting_participants.status <> 'active'
`

type JoinMeetingParams struct {
	MeetingID uuid.UUID `json:"meeting_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) JoinMeeting(ctx context.Context, arg JoinMeetingParams) (int64, error) {
	result, err := q.db.Exec(ctx, joinMeeting, arg.MeetingID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listMeetingParticipants = `-- name: ListMeetingParticipants :many
SELECT u.id AS user_id, u.display_name, mp.role, mp.joined_at
FROM meeting_participants mp
JOIN users u ON u.id = mp.user_id
WHERE mp.meeting_id = $1 AND mp.status = 'active'
ORDER BY (mp.role = 'owner') DESC, mp.joined_at, u.id
`

type ListMeetingParticipantsRow struct {
	UserID      uuid.UUID `json:"user_id"`
	DisplayName string    `json:"display_name"`
	Role        string    `json:"role"`
	JoinedAt    time.Time `json:"joined_at"`
}

func (q *Queries) ListMeetingParticipants(ctx context.Context, meetingID uuid.UUID) ([]ListMeetingParticipantsRow, error) {
	rows, err := q.db.Query(ctx, listMeetingParticipants, meetingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMeetingParticipantsRow{}
	for rows.Next() {
		var i ListMeetingParticipantsRow
		if err := rows.Scan(
			&i.UserID,
			&i.DisplayName,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlanOptions = `-- name: ListPlanOptions :many
SELECT id, meeting_id, title, description, position, idempotency_key, created_at
FROM plan_options
WHERE meeting_id = $1
ORDER BY position, created_at, id
`

func (q *Queries) ListPlanOptions(ctx context.Context, meetingID uuid.UUID) ([]PlanOption, error) {
	rows, err := q.db.Query(ctx, listPlanOptions, meetingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlanOption{}
	for rows.Next() {
		var i PlanOption
		if err := rows.Scan(
			&i.ID,
			&i.MeetingID,
			&i.Title,
			&i.Description,
			&i.Position,
			&i.IdempotencyKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimeOptions = `-- name: ListTimeOptions :many
SELECT id, meeting_id, starts_at, ends_at, position, idempotency_key, created_at, plan_option_id
FROM time_options
WHERE meeting_id = $1
ORDER BY position, starts_at, id
`

func (q *Queries) ListTimeOptions(ctx context.Context, meetingID uuid.UUID) ([]TimeOption, error) {
	rows, err := q.db.Query(ctx, listTimeOptions, meetingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TimeOption{}
	for rows.Next() {
		var i TimeOption
		if err := rows.Scan(
			&i.ID,
			&i.MeetingID,
			&i.StartsAt,
			&i.EndsAt,
			&i.Position,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.PlanOptionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockMeetingByID = `-- name: LockMeetingByID :one
SELECT id, state, coordination_mode, version
FROM meetings
WHERE id = $1
FOR UPDATE
`

type LockMeetingByIDRow struct {
	ID               uuid.UUID `json:"id"`
	State            string    `json:"state"`
	CoordinationMode string    `json:"coordination_mode"`
	Version          int64     `json:"version"`
}

func (q *Queries) LockMeetingByID(ctx context.Context, id uuid.UUID) (LockMeetingByIDRow, error) {
	row := q.db.QueryRow(ctx, lockMeetingByID, id)
	var i LockMeetingByIDRow
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.CoordinationMode,
		&i.Version,
	)
	return i, err
}

const nextPlanOptionPosition = `-- name: NextPlanOptionPosition :one
SELECT candidate::smallint
FROM generate_series(0, 19) AS candidate
WHERE NOT EXISTS (
    SELECT 1
    FROM plan_options
    WHERE meeting_id = $1 AND position = candidate
)
ORDER BY candidate
LIMIT 1
`

func (q *Queries) NextPlanOptionPosition(ctx context.Context, meetingID uuid.UUID) (int16, error) {
	row := q.db.QueryRow(ctx, nextPlanOptionPosition, meetingID)
	var candidate int16
	err := row.Scan(&candidate)
	return candidate, err
}

const nextTimeOptionPosition = `-- name: NextTimeOptionPosition :one
SELECT candidate::smallint
FROM generate_series(0, 19) AS candidate
WHERE NOT EXISTS (
    SELECT 1
    FROM time_options
    WHERE meeting_id = $1 AND position = candidate
)
ORDER BY candidate
LIMIT 1
`

func (q *Queries) NextTimeOptionPosition(ctx context.Context, meetingID uuid.UUID) (int16, error) {
	row := q.db.QueryRow(ctx, nextTimeOptionPosition, meetingID)
	var candidate int16
	err := row.Scan(&candidate)
	return candidate, err
}

const openMeetingCollection = `-- name: OpenMeetingCollection :exec
UPDATE meetings
SET state = 'collecting', version = version + 1, updated_at = now()
WHERE id = $1
`

func (q *Queries) OpenMeetingCollection(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, openMeetingCollection, id)
	return err
}

const planOptionBelongsToMeeting = `-- name: PlanOptionBelongsToMeeting :one
SELECT EXISTS (
    SELECT 1
    FROM plan_options
    WHERE id = $1 AND meeting_id = $2
)
`

type PlanOptionBelongsToMeetingParams struct {
	ID        uuid.UUID `json:"id"`
	MeetingID uuid.UUID `json:"meeting_id"`
}

func (q *Queries) PlanOptionBelongsToMeeting(ctx context.Context, arg PlanOptionBelongsToMeetingParams) (bool, error) {
	row := q.db.QueryRow(ctx, planOptionBelongsToMeeting, arg.ID, arg.MeetingID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const revokeActiveInvitations = `-- name: RevokeActiveInvitations :execrows
UPDATE invitations
SET revoked_at = now()
WHERE meeting_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeActiveInvitations(ctx context.Context, meetingID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeActiveInvitations, meetingID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchMeeting = `-- name: TouchMeeting :exec
UPDATE meetings
SET version = version + 1, updated_at = now()
WHERE id = $1
`

func (q *Queries) TouchMeeting(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchMeeting, id)
	return err
}

const updatePlanOption = `-- name: UpdatePlanOption :one
UPDATE plan_options
SET title = $3,
    description = $4
WHERE id = $1 AND meeting_id = $2
RETURNING id, meeting_id, title, description, position, idempotency_key, created_at
`

type UpdatePlanOptionParams struct {
	ID          uuid.UUID `json:"id"`
	MeetingID   uuid.UUID `json:"meeting_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
}

func (q *Queries) UpdatePlanOption(ctx context.Context, arg UpdatePlanOptionParams) (PlanOption, error) {
	row := q.db.QueryRow(ctx, updatePlanOption,
		arg.ID,
		arg.MeetingID,
		arg.Title,
		arg.Description,
	)
	var i PlanOption
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const updateTimeOption = `-- name: UpdateTimeOption :one
UPDATE time_options
SET plan_option_id = $3,
    starts_at = $4,
    ends_at = $5
WHERE id = $1 AND meeting_id = $2
RETURNING id, meeting_id, starts_at, ends_at, position, idempotency_key, created_at, plan_option_id
`

type UpdateTimeOptionParams struct {
	ID           uuid.UUID  `json:"id"`
	MeetingID    uuid.UUID  `json:"meeting_id"`
	PlanOptionID *uuid.UUID `json:"plan_option_id"`
	StartsAt     time.Time  `json:"starts_at"`
	EndsAt       *time.Time `json:"ends_at"`
}

func (q *Queries) UpdateTimeOption(ctx context.Context, arg UpdateTimeOptionParams) (TimeOption, error) {
	row := q.db.QueryRow(ctx, updateTimeOption,
		arg.ID,
		arg.MeetingID,
		arg.PlanOptionID,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i TimeOption
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.StartsAt,
		&i.EndsAt,
		&i.Position,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.PlanOptionID,
	)
	return i, err
}
