services:
  places-postgres:
    image: postgres:17
    container_name: ryden-places-postgres
    environment:
      POSTGRES_DB: ryden_places
      POSTGRES_USER: ryden_user
      POSTGRES_PASSWORD: ryden_password
    ports:
      - "5551:5432"
    volumes:
      - places_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ryden_user -d ryden_places"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  places_postgres_data: